package com.peternaggschga.gwent.data;

import androidx.room.Database;
import androidx.room.RoomDatabase;

/**
 * An abstract class extending RoomDatabase and representing the SQLite database of the application.
 * The implementation is generated by the Room framework.
 */
@Database(entities = {UnitEntity.class, RowEntity.class}, version = 1)
abstract class AppDatabase extends RoomDatabase {
    /**
     * Returns an object implementing the operations defined in UnitDao.
     *
     * @return UnitDao implementing DAO for `units` table.
     */
    abstract UnitDao units();

    /**
     * Returns an object implementing the operations defined in RowDao.
     *
     * @return RowDao implementing DAO for `rows` table.
     */
    abstract RowDao rows();
}
