Gwent: CardUiState Class Reference
CardUiState Class Reference
A data class encapsulating the visible state of a card in the card list shown by the ShowUnitsDialog.
Public Member Functions
CardUiState (int unitId, @DrawableRes int damageBackgroundImageId, @IntRange(from=UNUSED) int damage, @ColorInt int damageTextColor, @DrawableRes int abilityImageId, @Nullable @IntRange(from=1) Integer squad)
Constructor of a CardUiState encapsulating the given data.
boolean showAbility ()
Returns whether the ability view is shown, i.e., if the unit has an ability other than Ability::NONE.
boolean showSquad ()
Returns whether the squad view is shown, i.e., if the unit has the Ability::BINDING ability.
int getUnitId ()
Returns the #unitId of the represented UnitEntity.
int getDamageBackgroundImageId ()
Returns the drawable resource shown as the background of the damage view.
String getDamageString ()
Returns the String shown in the damage view.
int getDamageTextColor ()
Returns the text color of the damage view.
int getAbilityImageId ()
Returns the drawable resource shown in the ability view.
String getSquadString ()
Returns the String shown in the squad view.
boolean equals (Object o)
Checks whether the given Object looks the same as this CardUiState.
Static Public Attributes
static final DiffUtil.ItemCallback< CardUiState > DIFF_CALLBACK
DiffUtil.ItemCallback used to compare different CardUiState objects in a ListAdapter, e.g., CardListAdapter.
static final int UNUSED = -1
Integer that is used instead of a drawable resource to indicate the absence of a meaningful #abilityImage.
Private Attributes
final int unitId
Integer referencing the UnitEntity::id of the represented UnitEntity.
final int damageBackgroundImageId
Integer referencing the drawable resource shown as the background of the damage view.
final String damageString
String containing the number shown in the damage view or nothing if the represented UnitEntity is epic.
final int damageTextColor
Integer representing the text color of the damage view.
final int abilityImageId
Integer referencing the drawable resource shown in the ability view.
final String squadString
String containing the number shown in the squad view.
Detailed Description
A data class encapsulating the visible state of a card in the card list shown by the ShowUnitsDialog.
Can be created from the represented UnitEntity using CardUiStateFactory.
See also
CardUiStateFactory
ShowUnitsDialog
Definition at line 24 of file CardUiState.java.
Constructor & Destructor Documentation
CardUiState()
CardUiState (int unitId, @DrawableRes int damageBackgroundImageId, @IntRange(from=UNUSED) int damage, @ColorInt int damageTextColor, @DrawableRes int abilityImageId, @Nullable @IntRange(from=1) Integer squad)
Constructor of a CardUiState encapsulating the given data.
Parameters
unitId Integer representing the UnitEntity::id of the represented UnitEntity.
damageBackgroundImageId Integer referencing the drawable resource shown by the damage view.
damage Integer representing the damage of the represented UnitEntity.
damageTextColor Integer representing the text color of the damage view.
abilityImageId Integer referencing the drawable resource shown by the ability image view or #UNUSED.
squad Integer representing the UnitEntity::squad of the represented UnitEntity.
Exceptions
IllegalArgumentException When damage is less than #UNUSED or squad is neither null nor greater than zero.
See also
CardUiStateFactory::createCardUiState(UnitEntity, DamageCalculator)
Definition at line 108 of file CardUiState.java.
References CardUiState.abilityImageId, CardUiState.damageBackgroundImageId, CardUiState.damageTextColor, CardUiState.unitId, and CardUiState.UNUSED.
Member Function Documentation
equals()
boolean equals (Object o)
Checks whether the given Object looks the same as this CardUiState.
Does not compare #unitId since that field does not influence the visual representation of CardUiState objects.
Parameters
o Object that is being compared with this CardUiState.
Returns
A Boolean defining whether the objects look the same.
Definition at line 212 of file CardUiState.java.
References CardUiState.abilityImageId, CardUiState.damageBackgroundImageId, CardUiState.damageString, CardUiState.damageTextColor, CardUiState.equals(), and CardUiState.squadString.
Referenced by CardUiState.equals().
getAbilityImageId()
int getAbilityImageId ()
Returns the drawable resource shown in the ability view.
Returns
An Integer referencing a drawable resource.
See also
#abilityImageId
#showAbility()
Definition at line 189 of file CardUiState.java.
References CardUiState.abilityImageId.
Referenced by CardListAdapter.onBindViewHolder().
getDamageBackgroundImageId()
int getDamageBackgroundImageId ()
Returns the drawable resource shown as the background of the damage view.
Returns
An Integer referencing a drawable resource.
See also
#damageBackgroundImageId
Definition at line 158 of file CardUiState.java.
References CardUiState.damageBackgroundImageId.
Referenced by CardListAdapter.onBindViewHolder().
getDamageString()
String getDamageString ()
Returns the String shown in the damage view.
Returns
A String containing the damage of the represented UnitEntity or nothing if the unit is empty.
See also
#damageString
Definition at line 168 of file CardUiState.java.
References CardUiState.damageString.
Referenced by CardListAdapter.onBindViewHolder().
getDamageTextColor()
int getDamageTextColor ()
Returns the text color of the damage view.
Returns
An Integer representing a color.
See also
#damageTextColor
Definition at line 178 of file CardUiState.java.
References CardUiState.damageTextColor.
Referenced by CardListAdapter.onBindViewHolder().
getSquadString()
String getSquadString ()
Returns the String shown in the squad view.
Returns
A String containing the squad of the represented UnitEntity or nothing.
See also
#squadString
#showSquad()
Definition at line 200 of file CardUiState.java.
References CardUiState.squadString.
Referenced by CardListAdapter.onBindViewHolder().
getUnitId()
int getUnitId ()
Returns the #unitId of the represented UnitEntity.
See also
#unitId
Returns
An Integer referencing the UnitEntity::id of the represented UnitEntity.
Definition at line 148 of file CardUiState.java.
References CardUiState.unitId.
Referenced by CardListAdapter.onBindViewHolder().
showAbility()
boolean showAbility ()
Returns whether the ability view is shown, i.e., if the unit has an ability other than Ability::NONE.
Returns
A Boolean defining whether the ability view is shown.
Definition at line 130 of file CardUiState.java.
References CardUiState.abilityImageId, and CardUiState.UNUSED.
Referenced by CardListAdapter.onBindViewHolder(), and CardUiState.showSquad().
showSquad()
boolean showSquad ()
Returns whether the squad view is shown, i.e., if the unit has the Ability::BINDING ability.
Returns
A Boolean defining whether the squad view is shown.
Definition at line 139 of file CardUiState.java.
References CardUiState.showAbility(), and CardUiState.squadString.
Referenced by CardListAdapter.onBindViewHolder().
Member Data Documentation
abilityImageId
final int abilityImageId private
Integer referencing the drawable resource shown in the ability view.
May be #UNUSED if the view is not visible.
See also
#UNUSED
#getAbilityImageId()
Definition at line 88 of file CardUiState.java.
Referenced by CardUiState.CardUiState(), CardUiState.equals(), CardUiState.getAbilityImageId(), and CardUiState.showAbility().
damageBackgroundImageId
final int damageBackgroundImageId private
Integer referencing the drawable resource shown as the background of the damage view.
See also
#getDamageBackgroundImageId()
Definition at line 64 of file CardUiState.java.
Referenced by CardUiState.CardUiState(), CardUiState.equals(), and CardUiState.getDamageBackgroundImageId().
damageString
final String damageString private
String containing the number shown in the damage view or nothing if the represented UnitEntity is epic.
See also
#getDamageString()
Definition at line 72 of file CardUiState.java.
Referenced by CardUiState.equals(), and CardUiState.getDamageString().
damageTextColor
final int damageTextColor private
Integer representing the text color of the damage view.
See also
#getDamageTextColor()
Definition at line 79 of file CardUiState.java.
Referenced by CardUiState.CardUiState(), CardUiState.equals(), and CardUiState.getDamageTextColor().
DIFF_CALLBACK
final DiffUtil.ItemCallback<CardUiState> DIFF_CALLBACK static
Initial value:
= new DiffUtil.ItemCallback<CardUiState>() {
        @Override
        public boolean areItemsTheSame(@NonNull CardUiState oldItem, @NonNull CardUiState newItem) {
            return oldItem.unitId == newItem.unitId;
        }
        @Override
        public boolean areContentsTheSame(@NonNull CardUiState oldItem, @NonNull CardUiState newItem) {
            return Objects.equals(oldItem, newItem);
        }
    }
DiffUtil.ItemCallback used to compare different CardUiState objects in a ListAdapter, e.g., CardListAdapter.
See also
#unitId
#equals(Object)
Definition at line 33 of file CardUiState.java.
Referenced by CardListAdapter.CardListAdapter().
squadString
final String squadString private
String containing the number shown in the squad view.
See also
#getSquadString()
Definition at line 95 of file CardUiState.java.
Referenced by CardUiState.equals(), CardUiState.getSquadString(), and CardUiState.showSquad().
unitId
final int unitId private
Integer referencing the UnitEntity::id of the represented UnitEntity.
The only member that is not shown in the UI.
See also
#getUnitId()
Definition at line 57 of file CardUiState.java.
Referenced by CardUiState.CardUiState(), and CardUiState.getUnitId().
UNUSED
final int UNUSED = -1 static
Integer that is used instead of a drawable resource to indicate the absence of a meaningful #abilityImage.
See also
#abilityImageId
Definition at line 50 of file CardUiState.java.
Referenced by CardUiState.CardUiState(), CardUiStateFactory.createCardUiState(), and CardUiState.showAbility().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/cards/CardUiState.java