Gwent: HornDamageCalculatorDecorator Class Reference
HornDamageCalculatorDecorator Class Reference
A DamageCalculator class responsible for calculating the horn buff if necessary, i.e., if there are units with the com.peternaggschga.gwent.data.Ability::HORN ability that are not the unit the damage is calculated for or if there is a commander's horn in this row.
Public Member Functions
int calculateDamage (int id, @IntRange(from=0) int damage)
Calculates the (de-)buffed damage of unit with the given id and the given base-damage.
Color isBuffed (int id)
Calculates whether the unit with the given id is shown as Color::BUFFED, Color::DEBUFFED, or Color::DEFAULT.
Package Functions
HornDamageCalculatorDecorator (@NonNull DamageCalculator component, @NonNull List< Integer > unitIds)
Constructor of a HornDamageCalculatorDecorator.
Package Functions inherited from DamageCalculatorDecorator
DamageCalculatorDecorator (@NonNull DamageCalculator component)
Constructor of a DamageCalculatorDecorator.
Private Member Functions
boolean doubleDamage (int id)
Decides whether the unit with the given id is affected by the horn buff.
Private Attributes
final List< Integer > unitIds
A List of Integers containing the ids of all units with the com.peternaggschga.gwent.data.Ability::HORN ability.
Additional Inherited Members
Protected Attributes inherited from DamageCalculatorDecorator
final DamageCalculator component
A DamageCalculator which is decorated by this decorator.
Detailed Description
A DamageCalculator class responsible for calculating the horn buff if necessary, i.e., if there are units with the com.peternaggschga.gwent.data.Ability::HORN ability that are not the unit the damage is calculated for or if there is a commander's horn in this row.
Acts as a ConcreteDecorator in the implemented decorator pattern and should decorate a WeatherDamageCalculator, a BondDamageCalculatorDecorator or a MoralDamageCalculatorDecorator.
Definition at line 18 of file HornDamageCalculatorDecorator.java.
Constructor & Destructor Documentation
HornDamageCalculatorDecorator()
HornDamageCalculatorDecorator (@NonNull DamageCalculator component, @NonNull List< Integer > unitIds) package
Constructor of a HornDamageCalculatorDecorator.
Should only be called by DamageCalculatorBuilder. The given damage calculator should be of type WeatherDamageCalculator, BondDamageCalculatorDecorator or MoralDamageCalculatorDecorator for correct damage calculation. If the respective row has a commander's horn, null must be an element of the given List.
Parameters
component DamageCalculator that is being decorated by this decorator.
unitIds List of Integers representing ids of units with the com.peternaggschga.gwent.data.Ability::HORN ability.
See also
DamageCalculatorBuilder
Definition at line 38 of file HornDamageCalculatorDecorator.java.
References DamageCalculatorDecorator.component, and HornDamageCalculatorDecorator.unitIds.
Member Function Documentation
calculateDamage()
int calculateDamage (int id, @IntRange(from=0) int damage)
Calculates the (de-)buffed damage of unit with the given id and the given base-damage.
Returns given damage times two if the unit is buffed by a commander's horn.
See also
#doubleDamage(int)
Parameters
id Integer representing the UnitEntity::id of the unit whose (de-)buff damage is calculated.
damage Integer representing the base-damage of the unit whose (de-)buff damage is calculated.
Returns
Integer representing the (de-)buffed damage of the unit.
Exceptions
IllegalArgumentException When damage is negative.
Implements DamageCalculator.
Definition at line 63 of file HornDamageCalculatorDecorator.java.
References DamageCalculator.calculateDamage(), DamageCalculatorDecorator.component, and HornDamageCalculatorDecorator.doubleDamage().
doubleDamage()
boolean doubleDamage (int id) private
Decides whether the unit with the given id is affected by the horn buff.
Parameters
id Integer representing the UnitEntity::id of the unit that is being evaluated.
Returns
A Boolean value defining whether the horn buff affects the given unit.
Definition at line 49 of file HornDamageCalculatorDecorator.java.
References HornDamageCalculatorDecorator.unitIds.
Referenced by HornDamageCalculatorDecorator.calculateDamage(), and HornDamageCalculatorDecorator.isBuffed().
isBuffed()
Color isBuffed (int id)
Calculates whether the unit with the given id is shown as Color::BUFFED, Color::DEBUFFED, or Color::DEFAULT.
Units are shown as Color::BUFFED when they are affected by a horn buff, otherwise their Color is defined by #component.
Parameters
id Integer representing the UnitEntity::id of the unit buff status is calculated.
Returns
Color representing whether the unit is buffed, de-buffed or not affected.
See also
Color
#doubleDamage(int)
Implements DamageCalculator.
Definition at line 82 of file HornDamageCalculatorDecorator.java.
References DamageCalculatorDecorator.component, HornDamageCalculatorDecorator.doubleDamage(), and DamageCalculator.isBuffed().
Member Data Documentation
unitIds
final List<Integer> unitIds private
A List of Integers containing the ids of all units with the com.peternaggschga.gwent.data.Ability::HORN ability.
If a commander's horn is in the respective row, #unitIds contains null.
Definition at line 24 of file HornDamageCalculatorDecorator.java.
Referenced by HornDamageCalculatorDecorator.HornDamageCalculatorDecorator(), and HornDamageCalculatorDecorator.doubleDamage().
The documentation for this class was generated from the following file:
gwent/domain/damage/HornDamageCalculatorDecorator.java