Gwent: SoundManager Class Reference
SoundManager Class Reference
A class responsible for initializing and playing sounds when they are enabled.
Public Member Functions
SoundManager (@NonNull Context context)
Constructor of a SoundManager in the given Context.
void playSound (@IntRange(from=SOUND_WEATHER_GOOD, to=SOUND_COIN) int soundId)
Plays the given Sound if it is #activated.
void playClearWeatherSound ()
Plays the clear weather sound.
void playWeatherSound (@NonNull RowType row)
Plays the weather sound of the given row.
void playHornSound ()
Plays the horn sound.
void playCardAddSound (@NonNull RowType row, boolean epic)
Plays the card add sound for the given row.
void playCardRemovedSound ()
Plays the reset sound.
void playResetSound ()
Plays the reset sound.
void playBurnSound ()
Plays the burn sound.
void playCoinSound ()
Plays the coin sound.
Static Public Attributes
static final int SOUND_WEATHER_GOOD = 0
Constant Integer representing the clear weather sound.
static final int SOUND_WEATHER_FROST = 1
Constant Integer representing the frost weather sound.
static final int SOUND_WEATHER_FOG = 2
Constant Integer representing the fog weather sound.
static final int SOUND_WEATHER_RAIN = 3
Constant Integer representing the rain weather sound.
static final int SOUND_HORN = 4
Constant Integer representing the horn sound.
static final int SOUND_CARDS_EPIC = 5
Constant Integer representing the epic unit sound.
static final int SOUND_CARDS_MELEE = 6
Constant Integer representing the melee unit sound.
static final int SOUND_CARDS_RANGE = 7
Constant Integer representing the range unit sound.
static final int SOUND_CARDS_SIEGE = 8
Constant Integer representing the siege unit sound.
static final int SOUND_RESET = 9
Constant Integer representing the reset sound.
static final int SOUND_BURN = 10
Constant Integer representing the scorch sound.
static final int SOUND_COIN = 11
Constant Integer representing the coin-flip sound.
Private Attributes
final Sound[] sounds = new Sound[SOUND_COIN + 1]
Array of Sound objects representing the different sound effects.
final SoundPool soundPool
SoundPool where sound effects are registered.
final SharedPreferences.OnSharedPreferenceChangeListener changeListener
OnSharedPreferenceChangeListener that is registered for the default SharedPreferences and updates the Sound::active attributes of all #sounds when a preference change occurs.
Detailed Description
A class responsible for initializing and playing sounds when they are enabled.
See also
Sound
Definition at line 23 of file SoundManager.java.
Constructor & Destructor Documentation
SoundManager()
SoundManager (@NonNull Context context)
Constructor of a SoundManager in the given Context.
Creates a new #soundPool and registers #sounds using Sound::createSound(). Also registers a new #changeListener that updates the Sound::activated status when sound settings are updated.
Parameters
context Context, this SoundManager is used in.
See also
Sound::createSound(Context, int, SoundPool, int)
Definition at line 156 of file SoundManager.java.
References SoundManager.changeListener, Sound.createSound(), SoundManager.SOUND_BURN, SoundManager.SOUND_CARDS_EPIC, SoundManager.SOUND_CARDS_MELEE, SoundManager.SOUND_CARDS_RANGE, SoundManager.SOUND_CARDS_SIEGE, SoundManager.SOUND_COIN, SoundManager.SOUND_HORN, SoundManager.SOUND_RESET, SoundManager.SOUND_WEATHER_FOG, SoundManager.SOUND_WEATHER_FROST, SoundManager.SOUND_WEATHER_GOOD, SoundManager.SOUND_WEATHER_RAIN, SoundManager.soundPool, and SoundManager.sounds.
Member Function Documentation
playBurnSound()
void playBurnSound ()
Plays the burn sound.
Wrapper for #playSound().
See also
#playSound(int)
Definition at line 311 of file SoundManager.java.
References SoundManager.playSound(), and SoundManager.SOUND_BURN.
playCardAddSound()
void playCardAddSound (@NonNull RowType row, boolean epic)
Plays the card add sound for the given row.
If the unit is epic, the epic sound is played. Wrapper for #playSound().
Parameters
row RowType referencing the row for which the sound should be played.
epic Boolean defining whether the added unit is epic.
See also
#playSound(int)
Definition at line 268 of file SoundManager.java.
References SoundManager.playSound(), SoundManager.SOUND_CARDS_EPIC, SoundManager.SOUND_CARDS_MELEE, SoundManager.SOUND_CARDS_RANGE, and SoundManager.SOUND_CARDS_SIEGE.
playCardRemovedSound()
void playCardRemovedSound ()
Plays the reset sound.
Wrapper for #playSound().
See also
#playSound(int)
Definition at line 291 of file SoundManager.java.
References SoundManager.playSound(), and SoundManager.SOUND_RESET.
playClearWeatherSound()
void playClearWeatherSound ()
Plays the clear weather sound.
Wrapper for #playSound().
See also
#playSound(int)
Definition at line 225 of file SoundManager.java.
References SoundManager.playSound(), and SoundManager.SOUND_WEATHER_GOOD.
playCoinSound()
void playCoinSound ()
Plays the coin sound.
Wrapper for #playSound().
See also
#playSound(int)
Definition at line 320 of file SoundManager.java.
References SoundManager.playSound(), and SoundManager.SOUND_COIN.
playHornSound()
void playHornSound ()
Plays the horn sound.
Wrapper for #playSound().
See also
#playSound(int)
Definition at line 255 of file SoundManager.java.
References SoundManager.playSound(), and SoundManager.SOUND_HORN.
playResetSound()
void playResetSound ()
Plays the reset sound.
Wrapper for #playSound().
See also
#playSound(int)
Definition at line 301 of file SoundManager.java.
References SoundManager.playSound(), and SoundManager.SOUND_RESET.
playSound()
void playSound (@IntRange(from=SOUND_WEATHER_GOOD, to=SOUND_COIN) int soundId)
Plays the given Sound if it is #activated.
Given soundId must be either #SOUND_WEATHER_GOOD, #SOUND_WEATHER_FROST, #SOUND_WEATHER_FOG, #SOUND_WEATHER_RAIN, #SOUND_HORN, #SOUND_CARDS_EPIC, #SOUND_CARDS_MELEE, #SOUND_CARDS_RANGE, #SOUND_CARDS_SIEGE, #SOUND_RESET, #SOUND_BURN, or #SOUND_COIN, i.e., must be true. Alternately, #playClearWeatherSound(), #playWeatherSound(), #playHornSound(), #playCardAddSound(), #playCardRemovedSound(), #playResetSound(), #playBurnSound(), or #playCoinSound() may be used.
Parameters
soundId Integer representing the Sound that should be played.
Exceptions
IndexOutOfBoundsException When is not true.
Definition at line 213 of file SoundManager.java.
References SoundManager.soundPool, and SoundManager.sounds.
Referenced by SoundManager.playBurnSound(), SoundManager.playCardAddSound(), SoundManager.playCardRemovedSound(), SoundManager.playClearWeatherSound(), SoundManager.playCoinSound(), SoundManager.playHornSound(), SoundManager.playResetSound(), and SoundManager.playWeatherSound().
playWeatherSound()
void playWeatherSound (@NonNull RowType row)
Plays the weather sound of the given row.
Wrapper for #playSound().
Parameters
row RowType referencing the row for which the sound should be played.
See also
#playSound(int)
Definition at line 236 of file SoundManager.java.
References SoundManager.playSound(), SoundManager.SOUND_WEATHER_FOG, SoundManager.SOUND_WEATHER_FROST, and SoundManager.SOUND_WEATHER_RAIN.
Member Data Documentation
changeListener
final SharedPreferences.OnSharedPreferenceChangeListener changeListener private
OnSharedPreferenceChangeListener that is registered for the default SharedPreferences and updates the Sound::active attributes of all #sounds when a preference change occurs.
Reference must be kept (even if not used) to avoid garbage collection of the registered listener (see here for more information).
Definition at line 145 of file SoundManager.java.
Referenced by SoundManager.SoundManager().
SOUND_BURN
final int SOUND_BURN = 10 static
Constant Integer representing the scorch sound.
Index of the respective Sound object in #sounds.
See also
#playBurnSound()
Definition at line 110 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playBurnSound().
SOUND_CARDS_EPIC
final int SOUND_CARDS_EPIC = 5 static
Constant Integer representing the epic unit sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 70 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playCardAddSound().
SOUND_CARDS_MELEE
final int SOUND_CARDS_MELEE = 6 static
Constant Integer representing the melee unit sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 78 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playCardAddSound().
SOUND_CARDS_RANGE
final int SOUND_CARDS_RANGE = 7 static
Constant Integer representing the range unit sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 86 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playCardAddSound().
SOUND_CARDS_SIEGE
final int SOUND_CARDS_SIEGE = 8 static
Constant Integer representing the siege unit sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 94 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playCardAddSound().
SOUND_COIN
final int SOUND_COIN = 11 static
Constant Integer representing the coin-flip sound.
Index of the respective Sound object in #sounds.
See also
#playCoinSound()
Definition at line 118 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playCoinSound().
SOUND_HORN
final int SOUND_HORN = 4 static
Constant Integer representing the horn sound.
Index of the respective Sound object in #sounds.
See also
#playHornSound()
Definition at line 62 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playHornSound().
SOUND_RESET
final int SOUND_RESET = 9 static
Constant Integer representing the reset sound.
Index of the respective Sound object in #sounds.
See also
#playResetSound()
Definition at line 102 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), SoundManager.playCardRemovedSound(), and SoundManager.playResetSound().
SOUND_WEATHER_FOG
final int SOUND_WEATHER_FOG = 2 static
Constant Integer representing the fog weather sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 46 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playWeatherSound().
SOUND_WEATHER_FROST
final int SOUND_WEATHER_FROST = 1 static
Constant Integer representing the frost weather sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 38 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playWeatherSound().
SOUND_WEATHER_GOOD
final int SOUND_WEATHER_GOOD = 0 static
Constant Integer representing the clear weather sound.
Index of the respective Sound object in #sounds.
See also
#playClearWeatherSound()
Definition at line 30 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playClearWeatherSound().
SOUND_WEATHER_RAIN
final int SOUND_WEATHER_RAIN = 3 static
Constant Integer representing the rain weather sound.
Index of the respective Sound object in #sounds.
See also
#playCardAddSound(RowType, boolean)
Definition at line 54 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playWeatherSound().
soundPool
final SoundPool soundPool private
SoundPool where sound effects are registered.
Definition at line 134 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playSound().
sounds
final Sound [] sounds = new Sound[SOUND_COIN + 1] private
Array of Sound objects representing the different sound effects.
Indices are the public constants defined here, i.e., #SOUND_WEATHER_GOOD, #SOUND_WEATHER_FROST, #SOUND_WEATHER_FOG, #SOUND_WEATHER_RAIN, #SOUND_HORN, #SOUND_CARDS_EPIC, #SOUND_CARDS_MELEE, #SOUND_CARDS_RANGE, #SOUND_CARDS_SIEGE, #SOUND_RESET, #SOUND_BURN, and #SOUND_COIN.
Definition at line 128 of file SoundManager.java.
Referenced by SoundManager.SoundManager(), and SoundManager.playSound().
The documentation for this class was generated from the following file:
gwent/ui/sounds/SoundManager.java