Gwent: UnitEntity Class Reference
UnitEntity Class Reference
A class representing a card on the game board.
Public Member Functions
int calculateDamage (@NonNull DamageCalculator calculator)
Calculates the damage of this unit when (de-)buffed.
Color isBuffed (@NonNull DamageCalculator calculator)
Returns whether this unit is (de-)buffed.
String toString (@NonNull Context context)
Returns a string representation of this unit.
int getId ()
Getter for id.
boolean isEpic ()
Getter for epic.
int getDamage ()
Getter for damage.
Ability getAbility ()
Getter for ability.
Integer getSquad ()
Getter for squad.
RowType getRow ()
Getter for row.
Static Public Member Functions
static String collectionToString (@NonNull Context context, @NonNull Collection< UnitEntity > units)
Creates a String containing the descriptions of all units in the given collection, separated by commas.
Package Functions
UnitEntity (boolean epic, @IntRange(from=0) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row)
Constructor of a UnitEntity.
void setId (int id)
Setter for id.
void setEpic (boolean epic)
Setter for epic.
void setDamage (@IntRange(from=0) int damage)
Setter for damage.
void setAbility (@NonNull Ability ability)
Setter for ability.
void setSquad (@IntRange(from=1) @Nullable Integer squad)
Setter for squad.
void setRow (@NonNull RowType row)
Setter for row.
Private Attributes
int id
Defines the primary key of the represented unit.
boolean epic
Defines whether the represented card is epic.
int damage
Defines the base-damage of the represented card.
Ability ability
Defines the Ability of the represented card.
Integer squad
Defines the squad the unit belongs to if ability is Ability::BINDING.
RowType row
Defines the attack row the card lies in.
Detailed Description
A class representing a card on the game board.
Is a persistent Entity and is therefore saved in a database table named units.
Definition at line 36 of file UnitEntity.java.
Constructor & Destructor Documentation
UnitEntity()
UnitEntity (boolean epic, @IntRange(from=0) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row) package
Constructor of a UnitEntity.
id may not be set here since the value is generated automatically.
Parameters
epic Boolean representing whether card is epic.
damage Non-negative value representing the damage of the card.
ability Ability representing the ability of the card.
squad Integer representing the squad of a card that has the Ability::BINDING ability.
row RowType representing the combat type of the card.
Exceptions
IllegalArgumentException When damage is less than zero or if ability is Ability::BINDING and squad is null or less than one or if ability is not Ability::BINDING and squad is not null.
Definition at line 94 of file UnitEntity.java.
References Ability.BINDING.
Member Function Documentation
calculateDamage()
int calculateDamage (@NonNull DamageCalculator calculator)
Calculates the damage of this unit when (de-)buffed.
Returns damage if epic is true. Otherwise, the damage is calculated through the given DamageCalculator, which follows the visitor pattern.
Parameters
calculator DamageCalculator visitor used for damage calculation.
Returns
An Integer representing the units (de-)buffed damage.
See also
getDamage()
Definition at line 121 of file UnitEntity.java.
collectionToString()
static String collectionToString (@NonNull Context context, @NonNull Collection< UnitEntity > units) static
Creates a String containing the descriptions of all units in the given collection, separated by commas.
If n units have the same description, instead of printing the same description n times, "n×" is printed in front of the description. Unit descriptions are created using #toString(Context). Ordering of units in the given Collection is not guaranteed to be kept.
Parameters
context Context used to acquire String resources.
units Collection of UnitEntity objects that should be in the created String.
Returns
A String containing the description of all units.
Exceptions
IllegalArgumentException When units collection is empty.
See also
#toString(Context)
Definition at line 155 of file UnitEntity.java.
Referenced by BurnDialogUseCase.burn().
getAbility()
Ability getAbility ()
Getter for ability.
Returns
Ability representing the units' ability.
Definition at line 304 of file UnitEntity.java.
getDamage()
int getDamage ()
Getter for damage.
Returns
Integer representing the card's base-damage.
See also
#calculateDamage(DamageCalculator)
Definition at line 280 of file UnitEntity.java.
Referenced by SquadState.getState().
getId()
int getId ()
Getter for id.
Returns
Integer representing the units' id.
Definition at line 241 of file UnitEntity.java.
Referenced by UnitRepository.getUnitsFlowable(), DamageCalculatorBuildDirector.setHorns(), and DamageCalculatorBuildDirector.setMoralBoosts().
getRow()
RowType getRow ()
Getter for row.
Returns
RowType representing the units combat row.
Definition at line 351 of file UnitEntity.java.
getSquad()
Integer getSquad ()
Getter for squad.
Returns
Integer representing the units' squad if ability is Ability::BINDING or null.
Definition at line 324 of file UnitEntity.java.
isBuffed()
Color isBuffed (@NonNull DamageCalculator calculator)
Returns whether this unit is (de-)buffed.
Returns Color::DEFAULT if epic is true. Otherwise, whether the unit is (de-)buffed is calculated through the given DamageCalculator, which follows the visitor pattern.
Parameters
calculator DamageCalculator visitor used for damage calculation.
Returns
A Color representing the units (de-)buffed damage.
See also
getDamage()
Definition at line 136 of file UnitEntity.java.
isEpic()
boolean isEpic ()
Getter for epic.
Returns
Boolean representing whether the card is epic.
Definition at line 260 of file UnitEntity.java.
setAbility()
void setAbility (@NonNull Ability ability) package
Setter for ability.
Only used by Room extension.
Parameters
ability Ability representing the units' ability.
Definition at line 314 of file UnitEntity.java.
setDamage()
void setDamage (@IntRange(from=0) int damage) package
Setter for damage.
Only used by Room extension.
Parameters
damage Integer representing the card's base-damage.
Exceptions
IllegalArgumentException When damage is less than zero.
Definition at line 291 of file UnitEntity.java.
setEpic()
void setEpic (boolean epic) package
Setter for epic.
Only used by Room extension.
Parameters
epic Boolean representing whether the card is epic.
Definition at line 270 of file UnitEntity.java.
setId()
void setId (int id) package
Setter for id.
Only used by Room extension.
Parameters
id Integer representing the units' id.
Definition at line 251 of file UnitEntity.java.
setRow()
void setRow (@NonNull RowType row) package
Setter for row.
Only used by Room extension.
Parameters
row RowType representing the units combat row.
Definition at line 361 of file UnitEntity.java.
setSquad()
void setSquad (@IntRange(from=1) @Nullable Integer squad) package
Setter for squad.
Only used by Room extension.
Parameters
squad Integer representing the units' squad if ability is Ability::BINDING or null.
Exceptions
IllegalArgumentException When ability is Ability::BINDING and squad is null or less than 1 or if ability is not Ability::BINDING and squad is not null.
Definition at line 335 of file UnitEntity.java.
References Ability.BINDING.
toString()
String toString (@NonNull Context context)
Returns a string representation of this unit.
The representation contains information on each field of this class, i.e., row, epic, damage, ability, and squad.
Parameters
context Context used to acquire String resources.
Returns
A string representing the unit.
Definition at line 199 of file UnitEntity.java.
Member Data Documentation
ability
Ability ability private
Defines the Ability of the represented card.
Is set to Ability::NONE by default. Must not be null.
Definition at line 64 of file UnitEntity.java.
damage
int damage private
Defines the base-damage of the represented card.
Must be non-negative.
Definition at line 55 of file UnitEntity.java.
epic
boolean epic private
Defines whether the represented card is epic.
Is set to false by default.
Definition at line 49 of file UnitEntity.java.
id
int id private
Defines the primary key of the represented unit.
Is generated automatically on insert.
Definition at line 42 of file UnitEntity.java.
row
RowType row private
Defines the attack row the card lies in.
Must not be null.
Definition at line 81 of file UnitEntity.java.
squad
Integer squad private
Defines the squad the unit belongs to if ability is Ability::BINDING.
If ability is anything else, this value is null.
Definition at line 73 of file UnitEntity.java.
The documentation for this class was generated from the following file:
gwent/data/UnitEntity.java