Gwent: SquadState Class Reference
SquadState Class Reference
A data class encapsulating information about the squad defined by squadNumber, i.e., how many squadMembers are there and what is the memberBaseDamage of units in this squad.
Package Functions
boolean hasMembers ()
Returns whether the represented squad has members, i.e., whether squadMembers is greater than 0.
int getSquadNumber ()
Returns the number of the represented squad.
int getSquadMembers ()
Returns the number of members in the represented squad.
int getMemberBaseDamage ()
Returns the base damage of members in the represented squad.
Static Package Functions
static SquadState getState (@IntRange(from=1, to=MAX_NR_SQUADS) int squadNumber, @NonNull List< UnitEntity > units)
Creates a new SquadState representing the squad with the given squadNumber.
Private Member Functions
SquadState (@IntRange(from=1, to=MAX_NR_SQUADS) int squadNumber, @IntRange(from=0) int squadMembers, @IntRange(from=0, to=NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int memberBaseDamage)
Constructor of a SquadState with the given squadNumber, squadMembers, and memberBaseDamage.
Private Attributes
final int squadNumber
Integer containing the number of the represented squad.
final int squadMembers
Integer representing the number of members in the squad.
final int memberBaseDamage
Integer containing the base damage of members of this squad.
Detailed Description
A data class encapsulating information about the squad defined by squadNumber, i.e., how many squadMembers are there and what is the memberBaseDamage of units in this squad.
See also
SquadManager
Definition at line 19 of file SquadState.java.
Constructor & Destructor Documentation
SquadState()
SquadState (@IntRange(from=1, to=MAX_NR_SQUADS) int squadNumber, @IntRange(from=0) int squadMembers, @IntRange(from=0, to=NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int memberBaseDamage) private
Constructor of a SquadState with the given squadNumber, squadMembers, and memberBaseDamage.
Should only be used by getState().
Parameters
squadNumber Integer containing the number of the represented squad.
squadMembers Integer representing the number of members in the squad.
memberBaseDamage Integer containing the base damage of members of this squad.
See also
#getState(int, List)
Exceptions
IllegalArgumentException When one of the parameters doesn't meet its IntRange constraint.
Definition at line 55 of file SquadState.java.
References SquadState.memberBaseDamage, SquadState.squadMembers, and SquadState.squadNumber.
Referenced by SquadState.getState().
Member Function Documentation
getMemberBaseDamage()
int getMemberBaseDamage () package
Returns the base damage of members in the represented squad.
See also
memberBaseDamage
Returns
An Integer defining the base damage of units in the represented squad.
Definition at line 127 of file SquadState.java.
References SquadState.memberBaseDamage.
Referenced by SquadManager.onSquadChanged().
getSquadMembers()
int getSquadMembers () package
Returns the number of members in the represented squad.
See also
squadMembers
Returns
An Integer defining how many members are in the represented squad.
Definition at line 117 of file SquadState.java.
References SquadState.squadMembers.
Referenced by SquadManager.onSquadChanged().
getSquadNumber()
int getSquadNumber () package
Returns the number of the represented squad.
See also
squadNumber
Returns
An Integer defining which squad is represented.
Definition at line 107 of file SquadState.java.
References SquadState.squadNumber.
Referenced by SquadManager.getFirstSquadWithMembers(), and SquadManager.onSquadChanged().
getState()
static SquadState getState (@IntRange(from=1, to=MAX_NR_SQUADS) int squadNumber, @NonNull List< UnitEntity > units) static package
Creates a new SquadState representing the squad with the given squadNumber.
Information for squadMembers and memberBaseDamage is retrieved from the given List of UnitEntity objects.
Parameters
squadNumber Integer containing the number of the represented squad.
units List of UnitEntity objects used to count squad-members.
Returns
A SquadState object that is newly created from the given List of units.
Exceptions
IllegalArgumentException When the given squad number is not between 1 and #MAX_NR_SQUADS.
Definition at line 80 of file SquadState.java.
References SquadState.SquadState(), UnitEntity.getDamage(), and SquadState.squadNumber.
Referenced by SquadManager.SquadManager().
hasMembers()
boolean hasMembers () package
Returns whether the represented squad has members, i.e., whether squadMembers is greater than 0.
Returns
A Boolean defining whether the represented squad has members or not.
Definition at line 97 of file SquadState.java.
References SquadState.squadMembers.
Referenced by SquadManager.getFirstSquadWithMembers(), and SquadManager.onSquadChanged().
Member Data Documentation
memberBaseDamage
final int memberBaseDamage private
Integer containing the base damage of members of this squad.
If members have different UnitEntity::damage values, it is undefined which of them is picked. If squadMembers is 0, memberBaseDamage defaults to 5.
See also
getMemberBaseDamage()
Definition at line 43 of file SquadState.java.
Referenced by SquadState.SquadState(), and SquadState.getMemberBaseDamage().
squadMembers
final int squadMembers private
Integer representing the number of members in the squad.
See also
getSquadMembers()
Definition at line 34 of file SquadState.java.
Referenced by SquadState.SquadState(), SquadState.getSquadMembers(), and SquadState.hasMembers().
squadNumber
final int squadNumber private
Integer containing the number of the represented squad.
Equivalent to UnitEntity::squad of the units in the squad.
See also
getSquadNumber()
Definition at line 27 of file SquadState.java.
Referenced by SquadState.SquadState(), SquadState.getSquadNumber(), and SquadState.getState().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/addcard/SquadState.java