Gwent: GameBoardViewModel Class Reference
GameBoardViewModel Class Reference
An AndroidViewModel class responsible for encapsulating and offering state of views in activity_main.xml, i.e., that show the overall game board.
Public Member Functions
Flowable< RowUiState > getRowUiState (@NonNull RowType row)
Returns a Flowable object emitting RowUiState for the given row.
Flowable< MenuUiState > getMenuUiState ()
Returns a Flowable object emitting MenuUiState.
SoundManager getSoundManager ()
Returns the SoundManager managed by this GameBoardViewModel.
Completable onWeatherViewPressed (@NonNull RowType row)
Updates the weather debuff of the given row.
Completable onHornViewPressed (@NonNull RowType row)
Updates the horn buff of the given row.
Completable onResetButtonPressed (@NonNull Context context)
Triggers a reset and possibly an alert dialog, depending on preferences.
Completable onFactionSwitchReset (@NonNull Context context)
Triggers a reset and possibly an alert dialog, depending on preferences.
Completable onWeatherButtonPressed ()
Clears all weather effects.
Completable onBurnButtonPressed (@NonNull Context context)
Clears units with the most damage.
Static Public Member Functions
static GameBoardViewModel getModel (@NonNull ViewModelStoreOwner owner, @NonNull UnitRepository repository, @NonNull SoundManager soundManager)
Factory method of a GameBoardViewModel.
Private Member Functions
GameBoardViewModel (@NonNull GwentApplication application)
Constructor of a GameBoardViewModel object.
Single< UnitRepository > getRepository ()
Returns the UnitRepository used by the parent GwentApplication.
Completable reset (@NonNull Context context, @NonNull ResetDialogUseCase.Trigger trigger)
Triggers a reset and possibly an alert dialog, depending on preferences.
Private Attributes
final Map< RowType, Flowable< RowUiState > > rowUiStates = new HashMap<>(RowType.values().length)
A map structure containing the Flowable objects emitting the RowUiState for each row.
Flowable< MenuUiState > menuUiState = Flowable.empty()
Flowable emitting the MenuUiState for the right-hand side menu.
SoundManager soundManager
SoundManager used to play Sound effects on click events.
Static Private Attributes
static final ViewModelInitializer< GameBoardViewModel > INITIALIZER
ViewModelInitializer used by androidx.lifecycle.ViewModelProvider.Factory to instantiate the class.
Detailed Description
An AndroidViewModel class responsible for encapsulating and offering state of views in activity_main.xml, i.e., that show the overall game board.
Click events on the rows and the menu are handled also.
Definition at line 38 of file GameBoardViewModel.java.
Constructor & Destructor Documentation
GameBoardViewModel()
GameBoardViewModel (@NonNull GwentApplication application) private
Constructor of a GameBoardViewModel object.
Should only be called in #initializer.
Parameters
application GwentApplication that uses this AndroidViewModel.
See also
#INITIALIZER
Definition at line 60 of file GameBoardViewModel.java.
Member Function Documentation
getMenuUiState()
Flowable< MenuUiState > getMenuUiState ()
Returns a Flowable object emitting MenuUiState.
Returns
A Flowable object for the state of the menu.
See also
MenuUiState
#menuUiState
Definition at line 185 of file GameBoardViewModel.java.
References GameBoardViewModel.menuUiState.
Referenced by MainActivity.initializeViewModel().
getModel()
static GameBoardViewModel getModel (@NonNull ViewModelStoreOwner owner, @NonNull UnitRepository repository, @NonNull SoundManager soundManager) static
Factory method of a GameBoardViewModel.
Creates a new GameBoardViewModel for the given owner and initializes #rowUiStates and #menuUiState.
Parameters
owner ViewModelStoreOwner instantiating the GameBoardViewModel.
repository UnitRepository where Flowables are retrieved.
soundManager SoundManager used to play Sound effects on click events.
Returns
A new GameBoardViewModel instance.
See also
ViewModelProvider::ViewModelProvider(ViewModelStoreOwner, ViewModelProvider.Factory)
Definition at line 98 of file GameBoardViewModel.java.
References RowUiState.getDamage(), RowUiState.getUnits(), GameBoardViewModel.INITIALIZER, RowUiState.isHorn(), RowUiState.isWeather(), GameBoardViewModel.menuUiState, GameBoardViewModel.reset(), GameBoardViewModel.rowUiStates, and GameBoardViewModel.soundManager.
Referenced by MainActivity.onCreate().
getRepository()
Single< UnitRepository > getRepository () private
Returns the UnitRepository used by the parent GwentApplication.
Basically a wrapper for GwentApplication::getRepository(Context).
Returns
A Single emitting the UnitRepository instance.
See also
GwentApplication::getRepository(Context)
Definition at line 161 of file GameBoardViewModel.java.
References GwentApplication.getRepository().
Referenced by GameBoardViewModel.onHornViewPressed(), GameBoardViewModel.onWeatherButtonPressed(), and GameBoardViewModel.onWeatherViewPressed().
getRowUiState()
Flowable< RowUiState > getRowUiState (@NonNull RowType row)
Returns a Flowable object emitting RowUiState for the given row.
Parameters
row RowType defining the row for which the state is queried.
Returns
A Flowable object for the state of the given row.
See also
RowUiState
#rowUiStates
Definition at line 173 of file GameBoardViewModel.java.
References GameBoardViewModel.rowUiStates.
Referenced by MainActivity.initializeViewModel().
getSoundManager()
SoundManager getSoundManager ()
Returns the SoundManager managed by this GameBoardViewModel.
Returns
A SoundManager used by this GameBoardViewModel.
Definition at line 195 of file GameBoardViewModel.java.
References GameBoardViewModel.soundManager.
Referenced by MainActivity.inflateCoinFlipPopup(), and MainActivity.initializeViewModel().
onBurnButtonPressed()
Completable onBurnButtonPressed (@NonNull Context context)
Clears units with the most damage.
May inflate a warning dialog depending on the user's preferences and a Toast informing the user about the burned units. Should only be called by the View.OnClickListener of the burn button. Plays a matching sound, if units were removed.
Parameters
context Context
Returns
A Completable tracking operation status.
See also
BurnDialogUseCase::burn(Context, SoundManager)
Definition at line 310 of file GameBoardViewModel.java.
References GameBoardViewModel.soundManager.
Referenced by MainActivity.initializeViewModel().
onFactionSwitchReset()
Completable onFactionSwitchReset (@NonNull Context context)
Triggers a reset and possibly an alert dialog, depending on preferences.
Should only be called when the faction has been switched. Wrapper for #reset(Context, ResetDialogUseCase.Trigger).
Parameters
context Context object used to acquire SharedPreferences and inflate Dialog views.
Returns
A Completable tracking operation status.
See also
#reset(Context, ResetDialogUseCase.Trigger)
Definition at line 263 of file GameBoardViewModel.java.
References GameBoardViewModel.reset().
Referenced by MainActivity.inflateFactionPopup().
onHornViewPressed()
Completable onHornViewPressed (@NonNull RowType row)
Updates the horn buff of the given row.
Flips between on and off. Plays a matching sound, if the horn is switched on.
Parameters
row RowType defining the affected row.
Returns
A Completable tracking operation status.
See also
UnitRepository::switchHorn(RowType)
Definition at line 227 of file GameBoardViewModel.java.
References GameBoardViewModel.getRepository(), and GameBoardViewModel.soundManager.
Referenced by MainActivity.initializeViewModel().
onResetButtonPressed()
Completable onResetButtonPressed (@NonNull Context context)
Triggers a reset and possibly an alert dialog, depending on preferences.
Should only be called by the button's View.OnClickListener. Wrapper for #reset(Context, ResetDialogUseCase.Trigger).
Parameters
context Context object used to acquire SharedPreferences and inflate Dialog views.
Returns
A Completable tracking operation status.
See also
#reset(Context, ResetDialogUseCase.Trigger)
ResetDialogUseCase.Trigger::BUTTON_CLICK
Definition at line 250 of file GameBoardViewModel.java.
References GameBoardViewModel.reset().
Referenced by MainActivity.initializeViewModel().
onWeatherButtonPressed()
Completable onWeatherButtonPressed ()
Clears all weather effects.
Should only be called by the View.OnClickListener of the weather button. Plays a matching sound on completion.
Returns
A Completable tracking operation status.
See also
UnitRepository::clearWeather()
Definition at line 295 of file GameBoardViewModel.java.
References GameBoardViewModel.getRepository().
Referenced by MainActivity.initializeViewModel().
onWeatherViewPressed()
Completable onWeatherViewPressed (@NonNull RowType row)
Updates the weather debuff of the given row.
Flips between good and bad weather. Plays a matching sound, if the weather is switched on.
Parameters
row RowType defining the affected row.
Returns
A Completable tracking operation status.
See also
UnitRepository::switchWeather(RowType)
Definition at line 207 of file GameBoardViewModel.java.
References GameBoardViewModel.getRepository(), and GameBoardViewModel.soundManager.
Referenced by MainActivity.initializeViewModel().
reset()
Completable reset (@NonNull Context context, @NonNull ResetDialogUseCase.Trigger trigger) private
Triggers a reset and possibly an alert dialog, depending on preferences.
Plays a matching sound, if units were removed.
Parameters
context Context object used to acquire SharedPreferences and inflate Dialog views.
trigger com.peternaggschga.gwent.domain.cases.ResetDialogUseCase.Trigger defining which action triggered the reset.
Returns
A Completable tracking operation status.
See also
#reset(Context, ResetDialogUseCase.Trigger)
Definition at line 276 of file GameBoardViewModel.java.
References GameBoardViewModel.soundManager.
Referenced by GameBoardViewModel.getModel(), GameBoardViewModel.onFactionSwitchReset(), and GameBoardViewModel.onResetButtonPressed().
Member Data Documentation
INITIALIZER
final ViewModelInitializer<GameBoardViewModel> INITIALIZER static private
Initial value:
= new ViewModelInitializer<>(
            GameBoardViewModel.class,
            creationExtras -> {
                GwentApplication app = (GwentApplication) creationExtras.get(APPLICATION_KEY);
                assert app != null;
                return new GameBoardViewModel(app);
            })
ViewModelInitializer used by androidx.lifecycle.ViewModelProvider.Factory to instantiate the class.
See also
androidx.lifecycle.ViewModelProvider.Factory::from(ViewModelInitializer[])
Definition at line 45 of file GameBoardViewModel.java.
Referenced by GameBoardViewModel.getModel().
menuUiState
Flowable<MenuUiState> menuUiState = Flowable.empty() private
Flowable emitting the MenuUiState for the right-hand side menu.
Initialized in #getModel().
See also
#getMenuUiState()
MenuUiState
Definition at line 80 of file GameBoardViewModel.java.
Referenced by GameBoardViewModel.getMenuUiState(), and GameBoardViewModel.getModel().
rowUiStates
final Map<RowType, Flowable<RowUiState> > rowUiStates = new HashMap<>(RowType.values().length) private
A map structure containing the Flowable objects emitting the RowUiState for each row.
Initialized in #getModel().
See also
#getRowUiState(RowType)
RowUiState
Definition at line 71 of file GameBoardViewModel.java.
Referenced by GameBoardViewModel.getModel(), and GameBoardViewModel.getRowUiState().
soundManager
SoundManager soundManager private
SoundManager used to play Sound effects on click events.
Definition at line 85 of file GameBoardViewModel.java.
Referenced by GameBoardViewModel.getModel(), GameBoardViewModel.getSoundManager(), GameBoardViewModel.onBurnButtonPressed(), GameBoardViewModel.onHornViewPressed(), GameBoardViewModel.onWeatherViewPressed(), and GameBoardViewModel.reset().
The documentation for this class was generated from the following file:
gwent/ui/main/GameBoardViewModel.java