Gwent: DamageCalculatorBuilder Class Reference
DamageCalculatorBuilder Class Reference
A builder class responsible for creating a decorator structure of DamageCalculator classes with the given parameters.
Package Functions
void setWeather (boolean weather)
Sets the weather debuff for the calculation.
void setBond (@NonNull Map< Integer, Integer > idToSquad)
Sets the tight bond buff for the calculation.
void setMoral (@NonNull List< Integer > unitIds)
Sets the moral boost buff for the calculation.
void setHorn (@NonNull List< Integer > unitIds)
Sets the commander's horn buff for the calculation.
DamageCalculator getResult ()
Returns the current state of the built DamageCalculator, i.e.
Private Attributes
DamageCalculator calculator = new WeatherDamageCalculator(false)
The DamageCalculator instance that is being built by this DamageCalculatorBuilder.
Detailed Description
A builder class responsible for creating a decorator structure of DamageCalculator classes with the given parameters.
Should only be used by DamageCalculatorBuildDirector. Calls to #setWeather(), #setBond(), #setMoral() or #setHorn() should be in that exact order to create a correct DamageCalculator. Every function call is optional, i.e. every function should be called once or not at all.
See also
DamageCalculatorBuildDirector
DamageCalculator
DamageCalculatorDecorator
Definition at line 19 of file DamageCalculatorBuilder.java.
Member Function Documentation
getResult()
DamageCalculator getResult () package
Returns the current state of the built DamageCalculator, i.e.
#calculator.
Returns
A DamageCalculator that has been built by this builder.
Definition at line 72 of file DamageCalculatorBuilder.java.
References DamageCalculatorBuilder.calculator.
Referenced by DamageCalculatorBuildDirector.getCalculator().
setBond()
void setBond (@NonNull Map< Integer, Integer > idToSquad) package
Sets the tight bond buff for the calculation.
Should be called after #setWeather() or never.
Parameters
idToSquad Map mapping the ids of all units with the com.peternaggschga.gwent.data.Ability::BINDING ability to the respective squad size.
Definition at line 41 of file DamageCalculatorBuilder.java.
References DamageCalculatorBuilder.calculator.
setHorn()
void setHorn (@NonNull List< Integer > unitIds) package
Sets the commander's horn buff for the calculation.
Should be called after #setMoral() or never.
Parameters
unitIds List of Integers representing ids of units with the com.peternaggschga.gwent.data.Ability::HORN ability.
Definition at line 62 of file DamageCalculatorBuilder.java.
References DamageCalculatorBuilder.calculator.
setMoral()
void setMoral (@NonNull List< Integer > unitIds) package
Sets the moral boost buff for the calculation.
Should be called after #setBond() or never.
Parameters
unitIds List of Integers representing ids of units with the com.peternaggschga.gwent.data.Ability::MORAL_BOOST ability.
Definition at line 51 of file DamageCalculatorBuilder.java.
References DamageCalculatorBuilder.calculator.
setWeather()
void setWeather (boolean weather) package
Sets the weather debuff for the calculation.
Should be called first or never.
Parameters
weather Boolean defining whether the weather debuff is active.
Definition at line 32 of file DamageCalculatorBuilder.java.
References DamageCalculatorBuilder.calculator.
Referenced by DamageCalculatorBuildDirector.getCalculator().
Member Data Documentation
calculator
DamageCalculator calculator = new WeatherDamageCalculator(false) private
The DamageCalculator instance that is being built by this DamageCalculatorBuilder.
Starts as a WeatherDamageCalculator, since this is always at the end of the decorator chain.
Definition at line 25 of file DamageCalculatorBuilder.java.
Referenced by DamageCalculatorBuilder.getResult(), DamageCalculatorBuilder.setBond(), DamageCalculatorBuilder.setHorn(), DamageCalculatorBuilder.setMoral(), and DamageCalculatorBuilder.setWeather().
The documentation for this class was generated from the following file:
gwent/domain/damage/DamageCalculatorBuilder.java