Gwent: DamageCalculatorBuildDirector Class Reference
DamageCalculatorBuildDirector Class Reference
A build director responsible for the creation of DamageCalculator instances from sets of units using DamageCalculatorBuilder.
Static Public Member Functions
static DamageCalculator getCalculator (boolean weather, boolean horn, @NonNull Collection< UnitEntity > units)
Creates a DamageCalculator for a row with the given weather status, horn status and units.
Static Private Member Functions
static void setSquads (@NonNull Collection< UnitEntity > units, @NonNull DamageCalculatorBuilder builder)
Uses the given units to add a BondDamageCalculatorDecorator to the builder using DamageCalculatorBuilder::setBond().
static void setMoralBoosts (@NonNull Collection< UnitEntity > units, @NonNull DamageCalculatorBuilder builder)
Uses the given units to add a MoralDamageCalculatorDecorator to the builder using DamageCalculatorBuilder::setMoral().
static void setHorns (boolean horn, @NonNull Collection< UnitEntity > units, @NonNull DamageCalculatorBuilder builder)
Uses the given commander's horn status and the given units to add a HornDamageCalculatorDecorator to the builder using DamageCalculatorBuilder::setHorn().
Detailed Description
A build director responsible for the creation of DamageCalculator instances from sets of units using DamageCalculatorBuilder.
Encapsulates the logic for correct order of decorators.
See also
DamageCalculatorBuilder
Definition at line 21 of file DamageCalculatorBuildDirector.java.
Member Function Documentation
getCalculator()
static DamageCalculator getCalculator (boolean weather, boolean horn, @NonNull Collection< UnitEntity > units) static
Creates a DamageCalculator for a row with the given weather status, horn status and units.
Parameters
weather Boolean defining whether the calculation encompasses the weather debuff.
horn Boolean defining whether a commander's horn is in the row.
units Collection of UnitEntity objects that are in the row.
Returns
A DamageCalculator object capable of calculating damage for the given units.
Definition at line 31 of file DamageCalculatorBuildDirector.java.
References Ability.BINDING, DamageCalculatorBuilder.getResult(), Ability.HORN, Ability.MORAL_BOOST, DamageCalculatorBuildDirector.setHorns(), DamageCalculatorBuildDirector.setMoralBoosts(), DamageCalculatorBuildDirector.setSquads(), and DamageCalculatorBuilder.setWeather().
Referenced by DamageCalculatorUseCase.getDamageCalculator().
setHorns()
static void setHorns (boolean horn, @NonNull Collection< UnitEntity > units, @NonNull DamageCalculatorBuilder builder) static private
Uses the given commander's horn status and the given units to add a HornDamageCalculatorDecorator to the builder using DamageCalculatorBuilder::setHorn().
To accomplish this, the given unit list is converted to a List of the ids of the units with the Ability::HORN Ability (including null if horn is true).
Parameters
horn Boolean defining whether a commander's horn is in the row.
units Collection of UnitEntity objects that are in the row.
builder DamageCalculatorBuilder where the horn buff is added.
See also
DamageCalculatorBuilder::setHorn(List)
Definition at line 106 of file DamageCalculatorBuildDirector.java.
References UnitEntity.getId(), and Ability.HORN.
Referenced by DamageCalculatorBuildDirector.getCalculator().
setMoralBoosts()
static void setMoralBoosts (@NonNull Collection< UnitEntity > units, @NonNull DamageCalculatorBuilder builder) static private
Uses the given units to add a MoralDamageCalculatorDecorator to the builder using DamageCalculatorBuilder::setMoral().
To accomplish this, the given unit list is converted to a List of the ids of the units with the Ability::MORAL_BOOST Ability.
Parameters
units Collection of UnitEntity objects that are in the row.
builder DamageCalculatorBuilder where the horn buff is added.
See also
DamageCalculatorBuilder::setMoral(List)
Definition at line 85 of file DamageCalculatorBuildDirector.java.
References UnitEntity.getId(), and Ability.MORAL_BOOST.
Referenced by DamageCalculatorBuildDirector.getCalculator().
setSquads()
static void setSquads (@NonNull Collection< UnitEntity > units, @NonNull DamageCalculatorBuilder builder) static private
Uses the given units to add a BondDamageCalculatorDecorator to the builder using DamageCalculatorBuilder::setBond().
To accomplish this, the given unit list is converted to a Map from ids of units with the Ability::BINDING Ability to the respective squad size.
Parameters
units Collection of UnitEntity objects that are in the row.
builder DamageCalculatorBuilder where the horn buff is added.
See also
DamageCalculatorBuilder::setBond(Map)
Definition at line 61 of file DamageCalculatorBuildDirector.java.
References Ability.BINDING.
Referenced by DamageCalculatorBuildDirector.getCalculator().
The documentation for this class was generated from the following file:
gwent/domain/damage/DamageCalculatorBuildDirector.java