Gwent: ImageViewSwitchAnimator Class Reference
ImageViewSwitchAnimator Class Reference
A class providing functionality for changing the resource shown by an ImageView using a fading animation.
Static Public Member Functions
static Completable animatedSwitch (@NonNull ImageView view, @DrawableRes int resId)
Changes the resource of the given ImageView in an animation to the given resource id.
Static Private Member Functions
static ImageView getOverlayView (@NonNull ImageView template)
Returns a copy of the given template which is one layer above it.
Detailed Description
A class providing functionality for changing the resource shown by an ImageView using a fading animation.
See also
#animatedSwitch(ImageView, int)
Definition at line 20 of file ImageViewSwitchAnimator.java.
Member Function Documentation
animatedSwitch()
static Completable animatedSwitch (@NonNull ImageView view, @DrawableRes int resId) static
Changes the resource of the given ImageView in an animation to the given resource id.
Animation is realized by creating a new ImageView on top of the given ImageView which is then faded out using the fade_out animation provided by Android. The operation is complete when the animation ends.
See also
android.R.anim::fade_out
Parameters
view ImageView, whose resource is to be changed.
resId Integer representing the drawable resource that the given view should show.
Returns
A Completable tracking operation status.
Definition at line 53 of file ImageViewSwitchAnimator.java.
References ImageViewSwitchAnimator.getOverlayView().
Referenced by MenuUiStateObserver.accept(), RowUiStateObserver.accept(), and FactionSwitchListener.onSharedPreferenceChanged().
getOverlayView()
static ImageView getOverlayView (@NonNull ImageView template) static private
Returns a copy of the given template which is one layer above it.
Parameters
template ImageView that is copied.
Returns
An ImageView similar to template but one layer in front of it.
Definition at line 27 of file ImageViewSwitchAnimator.java.
Referenced by ImageViewSwitchAnimator.animatedSwitch().
The documentation for this class was generated from the following file:
gwent/ui/main/ImageViewSwitchAnimator.java