Gwent: RowUiState Class Reference
RowUiState Class Reference
A data class encapsulating the visible state of a row in the main view of the application.
Public Member Functions
RowUiState (@IntRange(from=0) int damage, boolean weather, boolean horn, @IntRange(from=0) int units)
Constructor of a RowUiState encapsulating the given data.
int getDamage ()
Returns the summed-up damage of all units in this row.
boolean isWeather ()
Returns whether the weather debuff is active in this row.
boolean isHorn ()
Returns whether the commander's horn buff is active in this row.
int getUnits ()
Returns the number of units in this row.
boolean equals (Object o)
Private Attributes
final int damage
Defines the summed-up damage of all units in this row.
final boolean weather
Defines whether the weather debuff is active in this row.
final boolean horn
Defines whether the commander's horn buff is active in this row.
final int units
Defines the number of units in this row.
Detailed Description
A data class encapsulating the visible state of a row in the main view of the application.
Definition at line 10 of file RowUiState.java.
Constructor & Destructor Documentation
RowUiState()
RowUiState (@IntRange(from=0) int damage, boolean weather, boolean horn, @IntRange(from=0) int units)
Constructor of a RowUiState encapsulating the given data.
Parameters
damage Integer representing the summed-up damage of all units.
weather Boolean defining whether the weather debuff is active.
horn Boolean defining whether the commander's horn buff is active.
units Integer representing the number of units.
Exceptions
IllegalArgumentException When damage or units is negative.
Definition at line 41 of file RowUiState.java.
References RowUiState.damage, RowUiState.horn, RowUiState.units, and RowUiState.weather.
Member Function Documentation
equals()
boolean equals (Object o)
Definition at line 89 of file RowUiState.java.
getDamage()
int getDamage ()
Returns the summed-up damage of all units in this row.
Returns
An Integer representing the summed-up damage of all units.
Definition at line 59 of file RowUiState.java.
References RowUiState.damage.
Referenced by GameBoardViewModel.getModel().
getUnits()
int getUnits ()
Returns the number of units in this row.
Returns
An Integer representing the number of units in this row.
Definition at line 84 of file RowUiState.java.
References RowUiState.units.
Referenced by GameBoardViewModel.getModel().
isHorn()
boolean isHorn ()
Returns whether the commander's horn buff is active in this row.
Returns
A Boolean whether the commander's horn buff is active.
Definition at line 75 of file RowUiState.java.
References RowUiState.horn.
Referenced by GameBoardViewModel.getModel().
isWeather()
boolean isWeather ()
Returns whether the weather debuff is active in this row.
Returns
A Boolean defining whether the weather debuff is active.
Definition at line 67 of file RowUiState.java.
References RowUiState.weather.
Referenced by GameBoardViewModel.getModel().
Member Data Documentation
damage
final int damage private
Defines the summed-up damage of all units in this row.
Definition at line 15 of file RowUiState.java.
Referenced by RowUiState.RowUiState(), and RowUiState.getDamage().
horn
final boolean horn private
Defines whether the commander's horn buff is active in this row.
Definition at line 25 of file RowUiState.java.
Referenced by RowUiState.RowUiState(), and RowUiState.isHorn().
units
final int units private
Defines the number of units in this row.
Definition at line 31 of file RowUiState.java.
Referenced by RowUiState.RowUiState(), and RowUiState.getUnits().
weather
final boolean weather private
Defines whether the weather debuff is active in this row.
Definition at line 20 of file RowUiState.java.
Referenced by RowUiState.RowUiState(), and RowUiState.isWeather().
The documentation for this class was generated from the following file:
gwent/ui/main/RowUiState.java