Gwent: DamageValuePicker Class Reference
DamageValuePicker Class Reference
A ValuePicker used for selection of damage values for UnitEntity::damage.
Static Public Attributes
static final Integer[] EPIC_DAMAGE_VALUES = new Integer[]{0, 7, 8, 10, 11, 15}
Integer array containing every damage value an epic unit may have.
static final int NON_EPIC_DAMAGE_VALUES_UPPER_BOUND = 20
Integer defining what the maximum damage of a non-epic UnitEntity can be.
Protected Member Functions
String getDisplayString (@NonNull Integer value)
Returns a localized String representing the given value when epicValues is false or otherwise the corresponding epic damage value.
Package Functions
DamageValuePicker (@NonNull NumberPicker picker)
Constructor of a DamageValuePicker wrapping the given NumberPicker.
void setValue (@NonNull @IntRange(from=0, to=NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) Integer value)
Sets the picker to the given value.
Integer getValue ()
Returns the currently selected value.
void setEpicValues (boolean epicValues)
Switches the #selectableValues between non-epic and epic damage values.
void setSelectableValues (@NonNull Collection< Integer > values, @Nullable Integer defaultValue)
Does nothing.
Private Attributes
boolean epicValues = false
Boolean defining whether or not this DamageValuePicker shows epic damage values.
Detailed Description
A ValuePicker used for selection of damage values for UnitEntity::damage.
Allows for switching between epic and normal damage values using setEpicValues().
Definition at line 23 of file DamageValuePicker.java.
Constructor & Destructor Documentation
DamageValuePicker()
DamageValuePicker (@NonNull NumberPicker picker) package
Constructor of a DamageValuePicker wrapping the given NumberPicker.
Calls setEpicValues() to initialize the NumberPicker with non-epic damage values.
See also
ValuePicker::ValuePicker(NumberPicker, SortedMap)
setEpicValues(boolean)
Parameters
picker NumberPicker wrapped by the created DamageValuePicker.
Definition at line 48 of file DamageValuePicker.java.
References DamageValuePicker.EPIC_DAMAGE_VALUES, and DamageValuePicker.setEpicValues().
Member Function Documentation
getDisplayString()
String getDisplayString (@NonNull Integer value) protected
Returns a localized String representing the given value when epicValues is false or otherwise the corresponding epic damage value.
Parameters
value Value that should be represented as a String.
Returns
A localized String representing the value.
Exceptions
IllegalStateException When epicValues is true and #displayIntegers does not contain a mapping for the given value.
Definition at line 66 of file DamageValuePicker.java.
References DamageValuePicker.epicValues.
getValue()
Integer getValue () package
Returns the currently selected value.
Returns
A value that is selected in #picker.
Definition at line 99 of file DamageValuePicker.java.
References DamageValuePicker.epicValues.
Referenced by CardNumberPickerAdapter.addSelectedUnits().
setEpicValues()
void setEpicValues (boolean epicValues) package
Switches the #selectableValues between non-epic and epic damage values.
Sets epicValues.
See also
epicValues
Parameters
epicValues Boolean defining whether or not epic values are shown.
Definition at line 109 of file DamageValuePicker.java.
References DamageValuePicker.EPIC_DAMAGE_VALUES, DamageValuePicker.epicValues, and DamageValuePicker.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and DamageValuePicker.DamageValuePicker().
setSelectableValues()
void setSelectableValues (@NonNull Collection< Integer > values, @Nullable Integer defaultValue) package
Does nothing.
Overrides parent since #selectableValues should only be modified by setEpicValues().
Parameters
values Collection of the new selectable values.
defaultValue Value that is shown in the beginning. If null, then the first value defined by the Comparable interface is used.
Definition at line 130 of file DamageValuePicker.java.
setValue()
void setValue (@NonNull @IntRange(from=0, to=NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) Integer value) package
Sets the picker to the given value.
If epicValues is true, ValuePicker::setValue() is called. Otherwise the #picker is simply set to the given value.
Parameters
value Value that the picker is set to.
Exceptions
IllegalStateException When epicValues is false and the given value is not in [0,20].
See also
ValuePicker::setValue(Comparable)
Definition at line 83 of file DamageValuePicker.java.
References DamageValuePicker.epicValues, and DamageValuePicker.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND.
Member Data Documentation
EPIC_DAMAGE_VALUES
final Integer [] EPIC_DAMAGE_VALUES = new Integer[]{0, 7, 8, 10, 11, 15} static
Integer array containing every damage value an epic unit may have.
Definition at line 28 of file DamageValuePicker.java.
Referenced by DamageValuePicker.DamageValuePicker(), and DamageValuePicker.setEpicValues().
epicValues
boolean epicValues = false private
Boolean defining whether or not this DamageValuePicker shows epic damage values.
See also
setEpicValues(boolean)
Definition at line 39 of file DamageValuePicker.java.
Referenced by DamageValuePicker.getDisplayString(), DamageValuePicker.getValue(), DamageValuePicker.setEpicValues(), and DamageValuePicker.setValue().
NON_EPIC_DAMAGE_VALUES_UPPER_BOUND
final int NON_EPIC_DAMAGE_VALUES_UPPER_BOUND = 20 static
Integer defining what the maximum damage of a non-epic UnitEntity can be.
Definition at line 33 of file DamageValuePicker.java.
Referenced by DamageValuePicker.setEpicValues(), and DamageValuePicker.setValue().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/addcard/DamageValuePicker.java