Gwent: AddCardDialog Class Reference
AddCardDialog Class Reference
An OverlayDialog used to add new UnitEntity objects to a certain #row.
Public Member Functions
AddCardDialog (@NonNull ShowUnitsDialog caller, @NonNull SoundManager soundManager)
Constructor of an AddCardDialog called by the given ShowUnitsDialog using the given SoundManager.
AddCardDialog (@NonNull Context context, @NonNull RowType row, @NonNull SoundManager soundManager)
Constructor of an AddCardDialog in the given Context and for the given row.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Initializes the #pickerAdapter if not yet done so and sets View.OnClickListener for each button.
Protected Member Functions inherited from OverlayDialog
OverlayDialog (@NonNull Context context, @LayoutRes int layout, @IdRes int dismissViewId)
Constructor of an OverlayDialog in the given Context, with the given layout and dismissViewId.
OverlayDialog (@NonNull Context context, @LayoutRes int layout)
Constructor of an OverlayDialog in the given Context and with the given layout.
Private Attributes
final RowType row
RowType defining the row the new UnitEntity objects are added to.
final SoundManager soundManager
SoundManager used to play a Sound whenever a card is added.
final CompositeDisposable disposables = new CompositeDisposable()
CompositeDisposable keeping track of all subscriptions to observables made by this class.
CardNumberPickerAdapter pickerAdapter = null
CardNumberPickerAdapter managing the connection to the NumberPicker views of this Dialog.
Additional Inherited Members
Static Package Attributes inherited from OverlayDialog
static final int NO_DISMISS_VIEW = -1
Integer used as #dismissViewId, when the Dialog shouldn't be cancelable by clicking on a View.
Detailed Description
An OverlayDialog used to add new UnitEntity objects to a certain #row.
Definition at line 22 of file AddCardDialog.java.
Constructor & Destructor Documentation
AddCardDialog() [1/2]
AddCardDialog (@NonNull ShowUnitsDialog caller, @NonNull SoundManager soundManager)
Constructor of an AddCardDialog called by the given ShowUnitsDialog using the given SoundManager.
Sets a Dialog.OnDismissListener disposing #disposables and showing the caller again. Wrapper of #AddCardDialog(Context, RowType, SoundManager).
See also
#AddCardDialog(Context, RowType, SoundManager)
Parameters
caller ShowUnitsDialog that called this Dialog.
soundManager SoundManager used to play a Sound when cards are added.
Definition at line 67 of file AddCardDialog.java.
References AddCardDialog.disposables, and AddCardDialog.soundManager.
AddCardDialog() [2/2]
AddCardDialog (@NonNull Context context, @NonNull RowType row, @NonNull SoundManager soundManager)
Constructor of an AddCardDialog in the given Context and for the given row.
Sets a Dialog.OnDismissListener disposing #disposables and showing the caller again.
Parameters
context Context this Dialog is shown in.
row RowType defining which row the new UnitEntity objects are added to.
soundManager SoundManager used to play a Sound when cards are added.
Definition at line 84 of file AddCardDialog.java.
References AddCardDialog.disposables, AddCardDialog.row, and AddCardDialog.soundManager.
Member Function Documentation
onCreate()
void onCreate (Bundle savedInstanceState) protected
Initializes the #pickerAdapter if not yet done so and sets View.OnClickListener for each button.
Parameters
savedInstanceState If this dialog is being reinitialized after the hosting activity was previously shut down, holds the result from the most recent call to onSaveInstanceState, or null if this is the first time.
Reimplemented from OverlayDialog.
Definition at line 102 of file AddCardDialog.java.
References CardNumberPickerAdapter.addSelectedUnits(), AddCardDialog.disposables, GwentApplication.getRepository(), AddCardDialog.pickerAdapter, and AddCardDialog.row.
Member Data Documentation
disposables
final CompositeDisposable disposables = new CompositeDisposable() private
CompositeDisposable keeping track of all subscriptions to observables made by this class.
Is being disposed in an android.content.DialogInterface.OnDismissListener that is set in #AddCardDialog(ShowUnitsDialog) and #AddCardDialog(Context, RowType).
See also
android.content.DialogInterface.OnDismissListener
#AddCardDialog(ShowUnitsDialog, SoundManager)
#AddCardDialog(Context, RowType, SoundManager)
Definition at line 47 of file AddCardDialog.java.
Referenced by AddCardDialog.AddCardDialog(), AddCardDialog.AddCardDialog(), and AddCardDialog.onCreate().
pickerAdapter
CardNumberPickerAdapter pickerAdapter = null private
CardNumberPickerAdapter managing the connection to the NumberPicker views of this Dialog.
Is lazily initialized in #onCreate().
See also
#onCreate(Bundle)
R.id::card_layout
Definition at line 57 of file AddCardDialog.java.
Referenced by AddCardDialog.onCreate().
row
final RowType row private
RowType defining the row the new UnitEntity objects are added to.
Definition at line 27 of file AddCardDialog.java.
Referenced by AddCardDialog.AddCardDialog(), and AddCardDialog.onCreate().
soundManager
final SoundManager soundManager private
SoundManager used to play a Sound whenever a card is added.
See also
SoundManager::playCardAddSound(RowType, boolean)
Definition at line 35 of file AddCardDialog.java.
Referenced by AddCardDialog.AddCardDialog(), and AddCardDialog.AddCardDialog().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/addcard/AddCardDialog.java