Gwent: RemoveUnitsUseCase Class Reference
RemoveUnitsUseCase Class Reference
A use case class responsible for removing units from a UnitRepository.
Static Public Member Functions
static Completable remove (@NonNull Context context, @NonNull UnitRepository repository, @NonNull Collection< UnitEntity > units, @NonNull SoundManager soundManager)
Removes the given UnitEntity objects from the given UnitRepository.
static Completable remove (@NonNull Context context, @NonNull UnitRepository repository, int id, @NonNull SoundManager soundManager)
Removes the unit with the given id from the given UnitRepository.
Static Private Member Functions
static Dialog getRevengeDialog (@NonNull Context context, @NonNull UnitRepository repository, @NonNull CompletableEmitter emitter, @NonNull Collection< UnitEntity > units, @IntRange(from=1) int revengeUnits, @NonNull SoundManager soundManager)
Creates a Dialog asking whether the Ability::REVENGE ability should be activated.
Detailed Description
A use case class responsible for removing units from a UnitRepository.
Capable of invoking a Dialog if a UnitEntity with the Ability::REVENGE ability is removed. Should not be used directly by the UI layer.
See also
BurnDialogUseCase
Definition at line 27 of file RemoveUnitsUseCase.java.
Member Function Documentation
getRevengeDialog()
static Dialog getRevengeDialog (@NonNull Context context, @NonNull UnitRepository repository, @NonNull CompletableEmitter emitter, @NonNull Collection< UnitEntity > units, @IntRange(from=1) int revengeUnits, @NonNull SoundManager soundManager) static private
Creates a Dialog asking whether the Ability::REVENGE ability should be activated.
The Dialog is created using an RevengeAlertDialogBuilderAdapter.
Parameters
context Context of the shown Dialog.
repository UnitRepository where the UnitEntity objects are removed and avengers are inserted.
emitter CompletableEmitter where CompletableEmitter::onComplete must be called, when the user makes a decision.
units Collection of UnitEntity objects that are removed.
revengeUnits Long representing the number of revenge units.
soundManager SoundManager used when an Avenger is added.
Returns
A Dialog asking whether the Ability::REVENGE ability should be activated.
See also
RevengeAlertDialogBuilderAdapter::insertAvengers(UnitRepository, int, SoundManager)
Definition at line 89 of file RemoveUnitsUseCase.java.
References RevengeAlertDialogBuilderAdapter.create(), RevengeAlertDialogBuilderAdapter.insertAvengers(), and RevengeAlertDialogBuilderAdapter.setPositiveCallback().
Referenced by RemoveUnitsUseCase.remove().
remove() [1/2]
static Completable remove (@NonNull Context context, @NonNull UnitRepository repository, @NonNull Collection< UnitEntity > units, @NonNull SoundManager soundManager) static
Removes the given UnitEntity objects from the given UnitRepository.
If a UnitEntity has the Ability::REVENGE ability, a Dialog asking whether the ability should be used is shown.
Parameters
context Context of the shown Dialog.
repository UnitRepository where the UnitEntity objects are removed.
units Collection of UnitEntity objects that are removed.
soundManager SoundManager used, if an UnitEntity has the Ability::REVENGE ability.
Returns
A Completable tracking operation status.
Exceptions
NullPointerException When units contains a null value.
See also
#getRevengeDialog(Context, UnitRepository, CompletableEmitter, Collection, int, SoundManager)
UnitRepository::delete(Collection)
Definition at line 43 of file RemoveUnitsUseCase.java.
References RemoveUnitsUseCase.getRevengeDialog().
remove() [2/2]
static Completable remove (@NonNull Context context, @NonNull UnitRepository repository, int id, @NonNull SoundManager soundManager) static
Removes the unit with the given id from the given UnitRepository.
If the unit has the Ability::REVENGE ability, a Dialog asking whether the ability should be used is shown. Wrapper of #remove(Context, UnitRepository, Collection).
Parameters
context Context of the shown Dialog.
repository UnitRepository where the UnitEntity objects are removed.
id Integer
Returns
A Completable tracking operation status.
See also
#remove(Context, UnitRepository, Collection, SoundManager)
Definition at line 68 of file RemoveUnitsUseCase.java.
The documentation for this class was generated from the following file:
gwent/domain/cases/RemoveUnitsUseCase.java