Gwent: CardUiStateFactory Class Reference
CardUiStateFactory Class Reference
A factory class responsible for creating CardUiState objects from UnitEntity objects.
Public Member Functions
CardUiStateFactory (@NonNull Context context, boolean weather, boolean horn)
Constructor of a CardUiStateFactory for a row with the given weather and horn (de-)buff values.
List< CardUiState > createCardUiState (@NonNull Collection< UnitEntity > units)
Creates a List of CardUiState objects from the given List of UnitEntity objects.
CardUiState createCardUiState (@NonNull UnitEntity unit, @NonNull DamageCalculator calculator)
Creates a CardUiState from the given UnitEntity.
Private Attributes
final boolean weather
Boolean defining the status of the weather debuff in the row for which CardUiState objects are created.
final boolean horn
Boolean defining the status of the horn buff in the row for which CardUiState objects are created.
final Map< Color, Integer > damageTextColors = new HashMap<>(Color.values().length)
Map containing a color integer for each Color value possible, i.e., Color::DEFAULT, Color::BUFFED, and Color::DEBUFFED.
Detailed Description
A factory class responsible for creating CardUiState objects from UnitEntity objects.
See also
CardUiState
Definition at line 28 of file CardUiStateFactory.java.
Constructor & Destructor Documentation
CardUiStateFactory()
CardUiStateFactory (@NonNull Context context, boolean weather, boolean horn)
Constructor of a CardUiStateFactory for a row with the given weather and horn (de-)buff values.
The Context parameter is used to retrieve the color values saved in #damageTextColors.
Parameters
context Context object used to get colors.
weather Boolean defining whether the weather debuff is active.
horn Boolean defining whether the horn buff is active.
See also
Context::getColor(int)
Definition at line 58 of file CardUiStateFactory.java.
References CardUiStateFactory.damageTextColors, CardUiStateFactory.horn, and CardUiStateFactory.weather.
Member Function Documentation
createCardUiState() [1/2]
List< CardUiState > createCardUiState (@NonNull Collection< UnitEntity > units)
Creates a List of CardUiState objects from the given List of UnitEntity objects.
Basically calls #createCardUiState(UnitEntity, DamageCalculator) for each given UnitEntity.
See also
#createCardUiState(UnitEntity, DamageCalculator)
Parameters
units List of UnitEntity objects that are converted to CardUiState objects.
Returns
A List of CardUiState objects from the given UnitEntity objects.
Definition at line 74 of file CardUiStateFactory.java.
References CardUiStateFactory.createCardUiState(), CardUiStateFactory.horn, and CardUiStateFactory.weather.
Referenced by CardUiStateFactory.createCardUiState().
createCardUiState() [2/2]
CardUiState createCardUiState (@NonNull UnitEntity unit, @NonNull DamageCalculator calculator)
Creates a CardUiState from the given UnitEntity.
See also
#createCardUiState(Collection)
Parameters
unit UnitEntity that is converted to a CardUiState.
calculator DamageCalculator used to calculate damage and Color of the given UnitEntity.
Returns
A CardUiState obtained from the given UnitEntity.
Definition at line 89 of file CardUiStateFactory.java.
References CardUiStateFactory.damageTextColors, and CardUiState.UNUSED.
Member Data Documentation
damageTextColors
final Map<Color, Integer> damageTextColors = new HashMap<>(Color.values().length) private
Map containing a color integer for each Color value possible, i.e., Color::DEFAULT, Color::BUFFED, and Color::DEBUFFED.
Definition at line 46 of file CardUiStateFactory.java.
Referenced by CardUiStateFactory.CardUiStateFactory(), and CardUiStateFactory.createCardUiState().
horn
final boolean horn private
Boolean defining the status of the horn buff in the row for which CardUiState objects are created.
Definition at line 39 of file CardUiStateFactory.java.
Referenced by CardUiStateFactory.CardUiStateFactory(), and CardUiStateFactory.createCardUiState().
weather
final boolean weather private
Boolean defining the status of the weather debuff in the row for which CardUiState objects are created.
Definition at line 33 of file CardUiStateFactory.java.
Referenced by CardUiStateFactory.CardUiStateFactory(), and CardUiStateFactory.createCardUiState().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/cards/CardUiStateFactory.java