Gwent: ResetDialogUseCase Class Reference
ResetDialogUseCase Class Reference
A use case class responsible for dispatching a reset call to ResetRepositoryUseCase, possibly after a confirmation by the user obtained from a Dialog.
Classes
enum DialogType
An Enum defining which form of Dialog should be shown.
enum Trigger
An Enum listing the possible triggers of a reset.
Static Public Member Functions
static Single< Boolean > reset (@NonNull Context context, @NonNull Trigger trigger, @NonNull SoundManager soundManager)
Resets the given UnitRepository.
Static Protected Member Functions
static Single< Boolean > reset (@NonNull Context context, @NonNull UnitRepository repository, @NonNull Trigger trigger, @NonNull SoundManager soundManager)
Resets the given UnitRepository.
Static Private Member Functions
static Single< DialogType > getDialogType (@NonNull Context context, @NonNull UnitRepository repository, @NonNull Trigger trigger)
Returns a DialogType defining which kind of Dialog should be invoked.
Detailed Description
A use case class responsible for dispatching a reset call to ResetRepositoryUseCase, possibly after a confirmation by the user obtained from a Dialog.
See also
ResetRepositoryUseCase
Definition at line 31 of file ResetDialogUseCase.java.
Member Function Documentation
getDialogType()
static Single< DialogType > getDialogType (@NonNull Context context, @NonNull UnitRepository repository, @NonNull Trigger trigger) static private
Returns a DialogType defining which kind of Dialog should be invoked.
Parameters
context Context used for retrieval of SharedPreferences.
repository UnitRepository used to check if a certain DialogType is even necessary.
trigger Trigger defining what triggered the reset.
Returns
A DialogType defining the kind of Dialog.
See also
DialogType
Definition at line 102 of file ResetDialogUseCase.java.
References ResetDialogUseCase.DialogType.DEFAULT, and ResetDialogUseCase.DialogType.NONE.
Referenced by ResetDialogUseCase.reset().
reset() [1/2]
static Single< Boolean > reset (@NonNull Context context, @NonNull Trigger trigger, @NonNull SoundManager soundManager) static
Resets the given UnitRepository.
May invoke a Dialog asking whether the user really wants to reset depending on the given trigger and warning settings. ResetRepositoryUseCase is used for resetting. Wrapper for #reset(Context, UnitRepository, Trigger).
Parameters
context Context where a Dialog can be inflated.
trigger Trigger defining what triggered this reset.
soundManager SoundManager used, if an UnitEntity has the Ability::REVENGE ability.
Returns
A Single emitting a Boolean defining whether the reset really took place.
See also
#reset(Context, UnitRepository, Trigger, SoundManager)
ResetRepositoryUseCase::reset(Context, UnitRepository, boolean, SoundManager)
Definition at line 47 of file ResetDialogUseCase.java.
References GwentApplication.getRepository(), and ResetDialogUseCase.reset().
Referenced by ResetDialogUseCase.reset().
reset() [2/2]
static Single< Boolean > reset (@NonNull Context context, @NonNull UnitRepository repository, @NonNull Trigger trigger, @NonNull SoundManager soundManager) static protected
Resets the given UnitRepository.
May invoke a Dialog asking whether the user really wants to reset depending on the given trigger and warning settings. ResetRepositoryUseCase is used for resetting.
Parameters
context Context where a Dialog can be inflated.
repository UnitRepository that is reset.
trigger Trigger defining what triggered this reset.
soundManager SoundManager used, if an UnitEntity has the Ability::REVENGE ability.
Returns
A Single emitting a Boolean defining whether the reset really took place.
See also
ResetRepositoryUseCase::reset(Context, UnitRepository, boolean, SoundManager)
Definition at line 66 of file ResetDialogUseCase.java.
References ResetAlertDialogBuilderAdapter.create(), ResetDialogUseCase.getDialogType(), ResetDialogUseCase.DialogType.MONSTER, ResetDialogUseCase.DialogType.NONE, ResetRepositoryUseCase.reset(), and ResetAlertDialogBuilderAdapter.setMonsterDialog().
The documentation for this class was generated from the following file:
gwent/domain/cases/ResetDialogUseCase.java