Gwent: RevengeAlertDialogBuilderAdapter Class Reference
RevengeAlertDialogBuilderAdapter Class Reference
An adapter class adapting AlertDialog.Builder to provide an interface for creating an AlertDialog asking the user whether they want to invoke the Ability::REVENGE ability.
Static Public Member Functions
static Completable insertAvengers (@NonNull UnitRepository repository, @IntRange(from=0) int numberOfAvengers)
Inserts numberOfAvengers avenger units into the given UnitRepository.
Package Functions
RevengeAlertDialogBuilderAdapter (@NonNull Context context)
Constructor of a RevengeAlertDialogBuilderAdapter.
AlertDialog create ()
Creates an AlertDialog with the arguments supplied to this builder.
RevengeAlertDialogBuilderAdapter setPositiveCallback (@NonNull DialogInterface.OnClickListener onPositiveButtonClick)
Adds the given callback to the positive button of the built Dialog.
RevengeAlertDialogBuilderAdapter setNegativeCallback (@NonNull DialogInterface.OnClickListener onNegativeButtonClick)
Adds the given callback to the negative button of the built Dialog.
Private Attributes
final AlertDialog.Builder adapteeBuilder
AlertDialog.Builder that is adapted by this class.
Static Private Attributes
static final boolean AVENGER_EPIC = false
Boolean constant defining whether the default UnitEntity summoned by the Ability::REVENGE ability is epic.
static final Ability AVENGER_ABILITY = Ability.NONE
Ability constant defining the Ability of the default UnitEntity summoned by the Ability::REVENGE ability.
static final int AVENGER_DAMAGE = 8
Integer constant defining the damage of the default UnitEntity summoned by the Ability::REVENGE ability.
static final Integer AVENGER_SQUAD = null
Integer constant defining the squad of the default UnitEntity summoned by the Ability::REVENGE ability.
static final RowType AVENGER_ROW = RowType.MELEE
RowType constant defining the row of the default UnitEntity summoned by the Ability::REVENGE ability.
Detailed Description
An adapter class adapting AlertDialog.Builder to provide an interface for creating an AlertDialog asking the user whether they want to invoke the Ability::REVENGE ability.
Definition at line 22 of file RevengeAlertDialogBuilderAdapter.java.
Constructor & Destructor Documentation
RevengeAlertDialogBuilderAdapter()
RevengeAlertDialogBuilderAdapter (@NonNull Context context) package
Constructor of a RevengeAlertDialogBuilderAdapter.
Initializes the buttons with empty callbacks.
Parameters
context Context of the built AlertDialog.
Definition at line 75 of file RevengeAlertDialogBuilderAdapter.java.
References RevengeAlertDialogBuilderAdapter.adapteeBuilder.
Member Function Documentation
create()
AlertDialog create () package
Creates an AlertDialog with the arguments supplied to this builder.
Basically just calls AlertDialog.Builder::create() on adapteeBuilder.
See also
AlertDialog.Builder::create()
Definition at line 106 of file RevengeAlertDialogBuilderAdapter.java.
References RevengeAlertDialogBuilderAdapter.adapteeBuilder.
Referenced by RemoveUnitsUseCase.getRevengeDialog(), and ResetRepositoryUseCase.getRevengeDialog().
insertAvengers()
static Completable insertAvengers (@NonNull UnitRepository repository, @IntRange(from=0) int numberOfAvengers) static
Inserts numberOfAvengers avenger units into the given UnitRepository.
The inserted UnitEntity objects have the attributes defined in AVENGER_EPIC, AVENGER_DAMAGE, AVENGER_ABILITY, AVENGER_SQUAD, and AVENGER_ROW.
Parameters
repository UnitRepository where avengers are inserted.
numberOfAvengers Integer defining how many avengers are inserted.
Returns
A Completable tracking operation status.
Definition at line 95 of file RevengeAlertDialogBuilderAdapter.java.
References RevengeAlertDialogBuilderAdapter.AVENGER_ABILITY, RevengeAlertDialogBuilderAdapter.AVENGER_DAMAGE, RevengeAlertDialogBuilderAdapter.AVENGER_EPIC, RevengeAlertDialogBuilderAdapter.AVENGER_ROW, and RevengeAlertDialogBuilderAdapter.AVENGER_SQUAD.
Referenced by RemoveUnitsUseCase.getRevengeDialog(), and ResetRepositoryUseCase.getRevengeDialog().
setNegativeCallback()
RevengeAlertDialogBuilderAdapter setNegativeCallback (@NonNull DialogInterface.OnClickListener onNegativeButtonClick) package
Adds the given callback to the negative button of the built Dialog.
Parameters
onNegativeButtonClick DialogInterface.OnClickListener that is called, when the negative button is clicked.
Returns
The RevengeAlertDialogBuilder with the updated negative callback.
Definition at line 131 of file RevengeAlertDialogBuilderAdapter.java.
References RevengeAlertDialogBuilderAdapter.adapteeBuilder.
setPositiveCallback()
RevengeAlertDialogBuilderAdapter setPositiveCallback (@NonNull DialogInterface.OnClickListener onPositiveButtonClick) package
Adds the given callback to the positive button of the built Dialog.
Callback should call insertAvengers().
Parameters
onPositiveButtonClick DialogInterface.OnClickListener that is called, when the positive button is clicked.
Returns
The RevengeAlertDialogBuilder with the updated positive callback.
See also
#insertAvengers(UnitRepository, int)
Definition at line 119 of file RevengeAlertDialogBuilderAdapter.java.
References RevengeAlertDialogBuilderAdapter.adapteeBuilder.
Referenced by RemoveUnitsUseCase.getRevengeDialog(), and ResetRepositoryUseCase.getRevengeDialog().
Member Data Documentation
adapteeBuilder
final AlertDialog.Builder adapteeBuilder private
AlertDialog.Builder that is adapted by this class.
Definition at line 67 of file RevengeAlertDialogBuilderAdapter.java.
Referenced by RevengeAlertDialogBuilderAdapter.RevengeAlertDialogBuilderAdapter(), RevengeAlertDialogBuilderAdapter.create(), RevengeAlertDialogBuilderAdapter.setNegativeCallback(), and RevengeAlertDialogBuilderAdapter.setPositiveCallback().
AVENGER_ABILITY
final Ability AVENGER_ABILITY = Ability.NONE static private
Ability constant defining the Ability of the default UnitEntity summoned by the Ability::REVENGE ability.
See also
Ability::REVENGE
Definition at line 37 of file RevengeAlertDialogBuilderAdapter.java.
Referenced by RevengeAlertDialogBuilderAdapter.insertAvengers().
AVENGER_DAMAGE
final int AVENGER_DAMAGE = 8 static private
Integer constant defining the damage of the default UnitEntity summoned by the Ability::REVENGE ability.
See also
Ability::REVENGE
Definition at line 45 of file RevengeAlertDialogBuilderAdapter.java.
Referenced by RevengeAlertDialogBuilderAdapter.insertAvengers().
AVENGER_EPIC
final boolean AVENGER_EPIC = false static private
Boolean constant defining whether the default UnitEntity summoned by the Ability::REVENGE ability is epic.
See also
Ability::REVENGE
Definition at line 29 of file RevengeAlertDialogBuilderAdapter.java.
Referenced by RevengeAlertDialogBuilderAdapter.insertAvengers().
AVENGER_ROW
final RowType AVENGER_ROW = RowType.MELEE static private
RowType constant defining the row of the default UnitEntity summoned by the Ability::REVENGE ability.
See also
Ability::REVENGE
Definition at line 61 of file RevengeAlertDialogBuilderAdapter.java.
Referenced by RevengeAlertDialogBuilderAdapter.insertAvengers().
AVENGER_SQUAD
final Integer AVENGER_SQUAD = null static private
Integer constant defining the squad of the default UnitEntity summoned by the Ability::REVENGE ability.
See also
Ability::REVENGE
Definition at line 53 of file RevengeAlertDialogBuilderAdapter.java.
Referenced by RevengeAlertDialogBuilderAdapter.insertAvengers().
The documentation for this class was generated from the following file:
gwent/domain/cases/RevengeAlertDialogBuilderAdapter.java