Gwent: GwentApplication Class Reference
GwentApplication Class Reference
An Application encapsulating the Gwent app.
Public Member Functions
void onCreate ()
Called when the application is starting, before any activity, service, or receiver objects (excluding content providers) have been created.
Single< UnitRepository > getRepository ()
Returns the repository used to create, read, update and delete game state.
Static Public Member Functions
static Single< UnitRepository > getRepository (@NonNull Context context)
Returns a UnitRepository used by the GwentApplication referenced by the given Context.
Private Attributes
AppDatabase database
AppDatabase used by this app.
Static Private Attributes
static UnitRepository repository = null
UnitRepository used for communication to database.
Detailed Description
An Application encapsulating the Gwent app.
This class is responsible for maintaining a Singleton UnitRepository connected to the AppDatabase of this app.
Definition at line 18 of file GwentApplication.java.
Member Function Documentation
getRepository() [1/2]
Single< UnitRepository > getRepository ()
Returns the repository used to create, read, update and delete game state.
Lazily initializes repository, if not yet done so.
See also
#getRepository(Context)
Returns
A UnitRepository used to access game state.
Definition at line 62 of file GwentApplication.java.
References GwentApplication.database, and GwentApplication.repository.
getRepository() [2/2]
static Single< UnitRepository > getRepository (@NonNull Context context) static
Returns a UnitRepository used by the GwentApplication referenced by the given Context.
Wrapper of getRepository().
See also
#getRepository()
Parameters
context Context of a GwentApplication.
Returns
A UnitRepository used by the given GwentApplication to access game state.
Definition at line 41 of file GwentApplication.java.
Referenced by CardNumberPickerAdapter.addSelectedUnits(), BurnDialogUseCase.burn(), ShowUnitsDialog.getDialog(), GameBoardViewModel.getRepository(), MainActivity.initializeViewModel(), MainActivity.onCreate(), AddCardDialog.onCreate(), and ResetDialogUseCase.reset().
onCreate()
void onCreate ()
Called when the application is starting, before any activity, service, or receiver objects (excluding content providers) have been created.
Initializes database.
Definition at line 51 of file GwentApplication.java.
References GwentApplication.database.
Member Data Documentation
database
AppDatabase database private
AppDatabase used by this app.
Is initialized in onCreate().
See also
#onCreate()
Definition at line 32 of file GwentApplication.java.
Referenced by GwentApplication.getRepository(), and GwentApplication.onCreate().
repository
UnitRepository repository = null static private
UnitRepository used for communication to database.
Is lazily initialized in getRepository() and provided as a Singleton.
See also
#getRepository()
#getRepository(Context)
Definition at line 25 of file GwentApplication.java.
Referenced by GwentApplication.getRepository().
The documentation for this class was generated from the following file:
gwent/GwentApplication.java