Gwent: BurnDialogUseCase Class Reference
BurnDialogUseCase Class Reference
A use case class responsible for dispatching a remove call to RemoveUnitsUseCase.
Static Public Member Functions
static Single< Boolean > burn (@NonNull Context context)
Burns the strongest UnitEntity objects in UnitRepository.
Static Protected Member Functions
static Single< Boolean > burn (@NonNull Context context, @NonNull UnitRepository repository)
Burns the strongest UnitEntity objects in UnitRepository.
Static Private Member Functions
static Single< List< UnitEntity > > getBurnUnits (@NonNull UnitRepository repository)
Returns the list of units that would be affected by a burn operation.
Detailed Description
A use case class responsible for dispatching a remove call to RemoveUnitsUseCase.
Definition at line 27 of file BurnDialogUseCase.java.
Member Function Documentation
burn() [1/2]
static Single<Boolean> burn (@NonNull Context context) static
Burns the strongest UnitEntity objects in UnitRepository.
Invokes a Dialog asking whether the user really wants to remove those units. ResetRepositoryUseCase is used for resetting. Wrapper for #burn(Context, UnitRepository).
Parameters
context Context where a Dialog can be inflated.
Returns
A Single emitting a Boolean defining whether the units really were burned.
See also
#burn(Context, UnitRepository)
RemoveUnitsUseCase::remove(Context, UnitRepository, Collection)
Definition at line 83 of file BurnDialogUseCase.java.
References GwentApplication.getRepository().
Referenced by GameBoardViewModel.onBurnButtonPressed().
burn() [2/2]
static Single<Boolean> burn (@NonNull Context context, @NonNull UnitRepository repository) static protected
Burns the strongest UnitEntity objects in UnitRepository.
Invokes a Dialog asking whether the user really wants to remove those units. ResetRepositoryUseCase is used for resetting.
Parameters
context Context where a Dialog can be inflated.
repository UnitRepository where units are burned.
Returns
A Single emitting a Boolean defining whether the units really were burned.
See also
RemoveUnitsUseCase::remove(Context, UnitRepository, Collection)
Definition at line 98 of file BurnDialogUseCase.java.
References UnitEntity.collectionToString().
getBurnUnits()
static Single<List<UnitEntity> > getBurnUnits (@NonNull UnitRepository repository) static private
Returns the list of units that would be affected by a burn operation.
The returned list may be empty.
Parameters
repository UnitRepository where units are fetched.
Returns
A Single emitting the List of UnitEntity objects that would be affected by the operation.
Definition at line 36 of file BurnDialogUseCase.java.
The documentation for this class was generated from the following file:
gwent/domain/cases/BurnDialogUseCase.java