Gwent: ChangeFactionDialog Class Reference
ChangeFactionDialog Class Reference
An OverlayDialog class used to change the faction design.
Classes
interface Callback
An interface used for propagating a selected theme back to the creator of a ChangeFactionDialog.
Public Member Functions
ChangeFactionDialog (@NonNull Context context, @NonNull Callback callback)
Constructor of a ChangeFactionDialog that calls the given Callback when one theme is selected.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Initializes layout and sets listeners for each view.
Protected Member Functions inherited from OverlayDialog
OverlayDialog (@NonNull Context context, @LayoutRes int layout, @IdRes int dismissViewId)
Constructor of an OverlayDialog in the given Context, with the given layout and dismissViewId.
OverlayDialog (@NonNull Context context, @LayoutRes int layout)
Constructor of an OverlayDialog in the given Context and with the given layout.
Private Member Functions
View.OnClickListener getOnThemeClickListener (@IntRange(from=THEME_MONSTER, to=THEME_SCOIATAEL) int theme)
Returns a View.OnclickListener instance that calls #cancel() and uses #callback to propagate the selected theme.
Private Attributes
final Callback callback
Callback that is called when a theme is selected.
Additional Inherited Members
Static Package Attributes inherited from OverlayDialog
static final int NO_DISMISS_VIEW = -1
Integer used as #dismissViewId, when the Dialog shouldn't be cancelable by clicking on a View.
Detailed Description
An OverlayDialog class used to change the faction design.
Definition at line 20 of file ChangeFactionDialog.java.
Constructor & Destructor Documentation
ChangeFactionDialog()
ChangeFactionDialog (@NonNull Context context, @NonNull Callback callback)
Constructor of a ChangeFactionDialog that calls the given Callback when one theme is selected.
Parameters
context Context in which this Dialog is run.
callback Callback that is called when a theme is selected.
Definition at line 33 of file ChangeFactionDialog.java.
References ChangeFactionDialog.callback.
Member Function Documentation
getOnThemeClickListener()
View.OnClickListener getOnThemeClickListener (@IntRange(from=THEME_MONSTER, to=THEME_SCOIATAEL) int theme) private
Returns a View.OnclickListener instance that calls #cancel() and uses #callback to propagate the selected theme.
Parameters
theme Integer representing the selected theme.
Returns
A View.OnClickListener handling theme input.
See also
#cancel()
Callback::onThemeSelect(int)
Definition at line 73 of file ChangeFactionDialog.java.
References ChangeFactionDialog.callback, and ChangeFactionDialog.Callback.onThemeSelect().
Referenced by ChangeFactionDialog.onCreate().
onCreate()
void onCreate (Bundle savedInstanceState) protected
Initializes layout and sets listeners for each view.
Parameters
savedInstanceState If this dialog is being reinitialized after the hosting activity was previously shut down, holds the result from the most recent call to onSaveInstanceState, or null if this is the first time.
Reimplemented from OverlayDialog.
Definition at line 47 of file ChangeFactionDialog.java.
References ChangeFactionDialog.getOnThemeClickListener().
Member Data Documentation
callback
final Callback callback private
Callback that is called when a theme is selected.
Definition at line 24 of file ChangeFactionDialog.java.
Referenced by ChangeFactionDialog.ChangeFactionDialog(), and ChangeFactionDialog.getOnThemeClickListener().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/ChangeFactionDialog.java