Gwent: UnitRepository Class Reference
UnitRepository Class Reference
A facade class managing public access to the data layer.
Public Member Functions
Completable reset ()
Resets the board by removing all units and resetting row status.
Completable reset (@Nullable UnitEntity keptUnit)
Resets the board by removing all units but the given one and resetting row status.
Completable insertUnit (boolean epic, @IntRange(from=0, to=UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row, @IntRange(from=0) int number)
Adds a number of units with the given stats to the given row.
Completable switchWeather (@NonNull RowType row)
Flips RowEntity::weather of the given attack row.
Single< Boolean > isWeather (@NonNull RowType row)
Returns the value of RowEntity::weather for the given attack row.
Flowable< Boolean > isWeatherFlowable (@NonNull RowType row)
Returns a Flowable emitting the latest value of RowEntity::weather for the given attack row.
Completable clearWeather ()
Sets RowEntity::weather to false for all attack rows.
Completable switchHorn (@NonNull RowType row)
Flips RowEntity::horn of the given attack row.
Single< Boolean > isHorn (@NonNull RowType row)
Returns the value of RowEntity::horn for the given attack row.
Flowable< Boolean > isHornFlowable (@NonNull RowType row)
Returns a Flowable emitting the values of RowEntity::horn for the given attack row.
Completable delete (@NonNull Collection< UnitEntity > units)
Removes the given units from the game.
Completable delete (int id)
Removes the unit with the given id from the game.
Completable copy (int id)
Copies the unit with the given id.
Single< Integer > countUnits (@NonNull RowType row)
Counts the units in the given attack row.
Single< Integer > countUnits ()
Counts the units in all attack rows.
Single< UnitEntity > getUnit (int id)
Returns the unit with the given id.
Single< List< UnitEntity > > getUnits (@NonNull RowType row)
Returns the units in the given attack row.
Flowable< List< UnitEntity > > getUnitsFlowable (@NonNull RowType row)
Returns a Flowable emitting the units in the given attack row.
Single< List< UnitEntity > > getUnits ()
Returns the units in the given attack row.
Flowable< Boolean > hasNonEpicUnitsFlowable ()
Returns a Flowable emitting Boolean values defining whether there are units in the game that are not epic.
Static Public Member Functions
static Single< UnitRepository > getRepository (@NonNull AppDatabase database)
Factory method for the UnitRepository class.
Private Member Functions
UnitRepository (@NonNull AppDatabase database)
Constructor of a UnitRepository.
Completable initializeRows ()
Adds one attack row for each RowType.
Completable insertUnit (boolean epic, @IntRange(from=0, to=UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row)
Adds a unit with the given stats to the given row.
Private Attributes
final AppDatabase database
Defines the AppDatabase that is used as a data source by this repository.
Detailed Description
A facade class managing public access to the data layer.
The contained functions mostly redirect requests to package-private DAO methods in RowDao and UnitDao. Some functions implement slightly more complex behavior by chaining multiple DAO calls, e.g., #reset().
Definition at line 25 of file UnitRepository.java.
Constructor & Destructor Documentation
UnitRepository()
UnitRepository (@NonNull AppDatabase database) private
Constructor of a UnitRepository.
Depends on the given AppDatabase as a data source. Should only be called by #getRepository().
Parameters
database AppDatabase that is injected for the repository.
See also
#getRepository(AppDatabase)
Definition at line 41 of file UnitRepository.java.
References UnitRepository.database.
Member Function Documentation
clearWeather()
Completable clearWeather ()
Sets RowEntity::weather to false for all attack rows.
Returns
A Completable tracking operation status.
Definition at line 208 of file UnitRepository.java.
References RowDao.clearWeather(), UnitRepository.database, and AppDatabase.rows().
copy()
Completable copy (int id)
Copies the unit with the given id.
Parameters
id Integer representing the unit that should be copied.
Returns
A Completable tracking operation status.
Definition at line 277 of file UnitRepository.java.
References UnitRepository.getUnit(), and UnitRepository.insertUnit().
countUnits() [1/2]
Single< Integer > countUnits ()
Counts the units in all attack rows.
Returns
A Single tracking operation status and returning the value.
See also
#countUnits(RowType)
Definition at line 302 of file UnitRepository.java.
References UnitDao.countUnits(), UnitRepository.database, and AppDatabase.units().
countUnits() [2/2]
Single< Integer > countUnits (@NonNull RowType row)
Counts the units in the given attack row.
Parameters
row RowEntity::id where the units are counted.
Returns
A Single tracking operation status and returning the value.
See also
#countUnits()
Definition at line 291 of file UnitRepository.java.
References UnitDao.countUnits(), UnitRepository.database, and AppDatabase.units().
delete() [1/2]
Completable delete (@NonNull Collection< UnitEntity > units)
Removes the given units from the game.
Parameters
units List of units to be removed.
Returns
A Completable tracking operation status.
Definition at line 256 of file UnitRepository.java.
References UnitRepository.database, UnitDao.deleteUnits(), and AppDatabase.units().
delete() [2/2]
Completable delete (int id)
Removes the unit with the given id from the game.
Parameters
id Integer representing the unit that should be deleted.
Returns
A Completable tracking operation status.
Definition at line 267 of file UnitRepository.java.
References UnitRepository.database, UnitDao.deleteUnit(), and AppDatabase.units().
getRepository()
static Single< UnitRepository > getRepository (@NonNull AppDatabase database) static
Factory method for the UnitRepository class.
Creates a new UnitRepository managing the given AppDatabase. Also initializes one RowEntity per RowType using #initializeRows().
See also
#initializeRows()
Parameters
database AppDatabase managed and initialized by the returned UnitRepository.
Returns
A Single emitting the created UnitRepository when initialization is finished.
Definition at line 54 of file UnitRepository.java.
References UnitRepository.database, and UnitRepository.initializeRows().
getUnit()
Single< UnitEntity > getUnit (int id)
Returns the unit with the given id.
Parameters
id Integer representing the queried unit.
Returns
A Single tracking operation status and returning the value.
Definition at line 313 of file UnitRepository.java.
References UnitRepository.database, UnitDao.getUnit(), and AppDatabase.units().
Referenced by UnitRepository.copy().
getUnits() [1/2]
Single< List< UnitEntity > > getUnits ()
Returns the units in the given attack row.
Returns
A Single tracking operation status and returning the value.
See also
#getUnits(RowType)
Definition at line 361 of file UnitRepository.java.
References UnitRepository.database, UnitDao.getUnits(), and AppDatabase.units().
getUnits() [2/2]
Single< List< UnitEntity > > getUnits (@NonNull RowType row)
Returns the units in the given attack row.
See also
#getUnitsFlowable(RowType)
Parameters
row RowEntity::id where the units have been placed.
Returns
A Single tracking operation status and returning the value.
See also
#getUnits()
Definition at line 325 of file UnitRepository.java.
References UnitRepository.database, UnitDao.getUnits(), and AppDatabase.units().
getUnitsFlowable()
Flowable< List< UnitEntity > > getUnitsFlowable (@NonNull RowType row)
Returns a Flowable emitting the units in the given attack row.
Parameters
row RowEntity::id where the units have been placed.
Returns
A Flowable emitting the values.
See also
#getUnits(RowType)
#getUnits()
Definition at line 338 of file UnitRepository.java.
References UnitRepository.database, UnitEntity.getId(), UnitDao.getUnitsFlowable(), and AppDatabase.units().
hasNonEpicUnitsFlowable()
Flowable< Boolean > hasNonEpicUnitsFlowable ()
Returns a Flowable emitting Boolean values defining whether there are units in the game that are not epic.
Returns
A Flowable emitting the values.
Definition at line 370 of file UnitRepository.java.
References UnitRepository.database, UnitDao.hasNonEpicUnitsFlowable(), and AppDatabase.units().
initializeRows()
Completable initializeRows () private
Adds one attack row for each RowType.
If an attack row already exists, it is not inserted again.
Returns
A Completable tracking operation status.
Definition at line 69 of file UnitRepository.java.
References UnitRepository.database, RowDao.insertRow(), and AppDatabase.rows().
Referenced by UnitRepository.getRepository(), and UnitRepository.reset().
insertUnit() [1/2]
Completable insertUnit (boolean epic, @IntRange(from=0, to=UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row) private
Adds a unit with the given stats to the given row.
Parameters
epic Boolean representing whether card is #epic.
damage Non-negative value representing the #damage of the card.
ability Ability representing the #ability of the card.
squad Integer representing the #squad of a card that has the Ability::BINDING #ability.
row RowType representing the combat type of the card.
Returns
A Completable tracking operation status.
Exceptions
IllegalArgumentException When damage is less than zero or if ability is Ability::BINDING and squad is null or less than zero or if ability is not Ability::BINDING and squad is not null.
Definition at line 119 of file UnitRepository.java.
References Ability.BINDING, UnitRepository.database, UnitEntity.EPIC_DAMAGE_VALUES, UnitDao.insertUnit(), UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND, and AppDatabase.units().
Referenced by UnitRepository.copy(), and UnitRepository.insertUnit().
insertUnit() [2/2]
Completable insertUnit (boolean epic, @IntRange(from=0, to=UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row, @IntRange(from=0) int number)
Adds a number of units with the given stats to the given row.
Essentially calls #insertUnit(boolean, int, Ability, Integer, RowType) multiple times.
Parameters
epic Boolean representing whether card is #epic.
damage Non-negative value representing the #damage of the card.
ability Ability representing the #ability of the card.
squad Integer representing the #squad of a card that has the Ability::BINDING #ability.
row RowType representing the combat type of the card.
number Integer representing the number of units to be added.
Returns
A Completable tracking operation status.
See also
#insertUnit(boolean, int, Ability, Integer, RowType)
Exceptions
IllegalArgumentException When damage is less than zero or if ability is Ability::BINDING and squad is null or less than zero or if ability is not Ability::BINDING and squad is not null.
Definition at line 153 of file UnitRepository.java.
References UnitRepository.insertUnit().
isHorn()
Single< Boolean > isHorn (@NonNull RowType row)
Returns the value of RowEntity::horn for the given attack row.
See also
#isHornFlowable(RowType)
Parameters
row RowEntity::id where the horn status is queried.
Returns
A Single tracking operation status and returning the value.
Definition at line 229 of file UnitRepository.java.
References UnitRepository.database, RowDao.isHorn(), and AppDatabase.rows().
isHornFlowable()
Flowable< Boolean > isHornFlowable (@NonNull RowType row)
Returns a Flowable emitting the values of RowEntity::horn for the given attack row.
Parameters
row RowEntity::id where the horn status is queried.
Returns
A Flowable emitting the values.
See also
#isHorn(RowType)
Definition at line 241 of file UnitRepository.java.
References UnitRepository.database, RowDao.isHornFlowable(), and AppDatabase.rows().
isWeather()
Single< Boolean > isWeather (@NonNull RowType row)
Returns the value of RowEntity::weather for the given attack row.
See also
#isWeatherFlowable(RowType)
Parameters
row RowEntity::id where the weather is queried.
Returns
A Single tracking operation status and returning the value.
Definition at line 181 of file UnitRepository.java.
References UnitRepository.database, RowDao.isWeather(), and AppDatabase.rows().
isWeatherFlowable()
Flowable< Boolean > isWeatherFlowable (@NonNull RowType row)
Returns a Flowable emitting the latest value of RowEntity::weather for the given attack row.
Parameters
row RowEntity::id where the weather is queried.
Returns
A Flowable emitting the values.
See also
#isWeather(RowType)
Definition at line 193 of file UnitRepository.java.
References UnitRepository.database, RowDao.isWeatherFlowable(), and AppDatabase.rows().
reset() [1/2]
Completable reset ()
Resets the board by removing all units and resetting row status.
Resetting row status is equivalent to removing the old rows and calling #initializeRows(). Method is a wrapper for #reset(UnitEntity).
Returns
A Completable tracking operation status.
See also
#reset(UnitEntity)
Definition at line 86 of file UnitRepository.java.
References UnitRepository.reset().
Referenced by UnitRepository.reset().
reset() [2/2]
Completable reset (@Nullable UnitEntity keptUnit)
Resets the board by removing all units but the given one and resetting row status.
Resetting row status is equivalent to removing the old rows and calling #initializeRows().
Parameters
keptUnit UnitEntity that should be kept.
Returns
A Completable tracking operation status.
See also
#initializeRows()
Definition at line 99 of file UnitRepository.java.
References RowDao.clearRows(), UnitRepository.database, UnitRepository.initializeRows(), UnitDao.insertUnit(), AppDatabase.rows(), and AppDatabase.units().
switchHorn()
Completable switchHorn (@NonNull RowType row)
Flips RowEntity::horn of the given attack row.
Parameters
row RowEntity::id where the horn status should be updated.
Returns
A Completable tracking operation status.
Definition at line 218 of file UnitRepository.java.
References UnitRepository.database, AppDatabase.rows(), and RowDao.updateHorn().
switchWeather()
Completable switchWeather (@NonNull RowType row)
Flips RowEntity::weather of the given attack row.
Parameters
row RowEntity::id where the weather should be updated.
Returns
A Completable tracking operation status.
Definition at line 170 of file UnitRepository.java.
References UnitRepository.database, AppDatabase.rows(), and RowDao.updateWeather().
Member Data Documentation
database
final AppDatabase database private
Defines the AppDatabase that is used as a data source by this repository.
Is provided by dependency injection in #UnitRepository().
Definition at line 31 of file UnitRepository.java.
Referenced by UnitRepository.UnitRepository(), UnitRepository.clearWeather(), UnitRepository.countUnits(), UnitRepository.countUnits(), UnitRepository.delete(), UnitRepository.delete(), UnitRepository.getRepository(), UnitRepository.getUnit(), UnitRepository.getUnits(), UnitRepository.getUnits(), UnitRepository.getUnitsFlowable(), UnitRepository.hasNonEpicUnitsFlowable(), UnitRepository.initializeRows(), UnitRepository.insertUnit(), UnitRepository.isHorn(), UnitRepository.isHornFlowable(), UnitRepository.isWeather(), UnitRepository.isWeatherFlowable(), UnitRepository.reset(), UnitRepository.switchHorn(), and UnitRepository.switchWeather().
The documentation for this class was generated from the following file:
gwent/data/UnitRepository.java