Gwent: CardNumberPickerAdapter Class Reference
CardNumberPickerAdapter Class Reference
A helper class responsible for initializing the NumberPicker views of an AddCardDialog (in #CardNumperPickerAdapter()) and adding UnitEntity objects with the selected attributes when #addSelectedUnits() is called.
Package Functions
CardNumberPickerAdapter (@NonNull ViewGroup pickerGroup, @NonNull SquadManager squadManager)
Constructor of a CardNumberPickerAdapter managing the NumberPicker views in the given ViewGroup using the given SquadManager.
Single< Boolean > addSelectedUnits (@NonNull RowType row)
Adds new UnitEntity objects the attributes selected by the managed pickers.
Static Package Functions
static NumberPicker.OnValueChangeListener getDelayedOnValueChangeListener (@NonNull NumberPicker.OnValueChangeListener originalListener)
Creates a NumberPicker.OnValueChangeListener that only executes the given NumberPicker.OnValueChangeListener after 500 ms if the value has not changed.
Private Attributes
final ValuePicker< Boolean > epicPicker
ValuePicker used to decide the value of UnitEntity::epic.
final DamageValuePicker damagePicker
DamageValuePicker used to decide the value of UnitEntity::damage.
final ValuePicker< Ability > abilityPicker
ValuePicker used to decide the value of UnitEntity::ability.
final NumberPicker squadPicker
NumberPicker used to decide the value of UnitEntity::squad.
final SquadManager squadManager
SquadManager containing current SquadState used to get squad information.
final NumberPicker numberPicker
NumberPicker used to decide the number of UnitEntity objects that are inserted.
Static Private Attributes
static final List< Ability > EPIC_UNIT_ABILITIES = Arrays.asList(Ability.NONE, Ability.HORN, Ability.MORAL_BOOST)
List of Ability values that epic units can have.
Detailed Description
A helper class responsible for initializing the NumberPicker views of an AddCardDialog (in #CardNumperPickerAdapter()) and adding UnitEntity objects with the selected attributes when #addSelectedUnits() is called.
See also
AddCardDialog
Definition at line 33 of file CardNumberPickerAdapter.java.
Constructor & Destructor Documentation
CardNumberPickerAdapter()
CardNumberPickerAdapter (@NonNull ViewGroup pickerGroup, @NonNull SquadManager squadManager) package
Constructor of a CardNumberPickerAdapter managing the NumberPicker views in the given ViewGroup using the given SquadManager.
Sets value bounds and NumberPicker.OnValueChangedListener for the pickers in the ViewGroup. The ViewGroup must be the ConstraintLayout with the id R.id::card_layout from popup_add_card.xml.
See also
R.id::card_layout
Parameters
pickerGroup ViewGroup containing the managed NumberPicker views.
squadManager SquadManager containing up-to-date SquadState.
Definition at line 89 of file CardNumberPickerAdapter.java.
References CardNumberPickerAdapter.abilityPicker, CardNumberPickerAdapter.damagePicker, CardNumberPickerAdapter.EPIC_UNIT_ABILITIES, CardNumberPickerAdapter.epicPicker, CardNumberPickerAdapter.getDelayedOnValueChangeListener(), SquadManager.getFirstSquadWithMembers(), SquadManager.MAX_NR_SQUADS, CardNumberPickerAdapter.numberPicker, SquadManager.onSquadChanged(), DamageValuePicker.setEpicValues(), CardNumberPickerAdapter.squadManager, and CardNumberPickerAdapter.squadPicker.
Member Function Documentation
addSelectedUnits()
Single< Boolean > addSelectedUnits (@NonNull RowType row) package
Adds new UnitEntity objects the attributes selected by the managed pickers.
Parameters
row RowType defining to which row the units are added.
Returns
A Single tracking operation status and containing whether the added unit is epic or not.
Definition at line 166 of file CardNumberPickerAdapter.java.
References CardNumberPickerAdapter.abilityPicker, CardNumberPickerAdapter.damagePicker, CardNumberPickerAdapter.epicPicker, SquadManager.getFirstSquadWithMembers(), GwentApplication.getRepository(), DamageValuePicker.getValue(), CardNumberPickerAdapter.numberPicker, CardNumberPickerAdapter.squadManager, and CardNumberPickerAdapter.squadPicker.
Referenced by AddCardDialog.onCreate().
getDelayedOnValueChangeListener()
static NumberPicker.OnValueChangeListener getDelayedOnValueChangeListener (@NonNull NumberPicker.OnValueChangeListener originalListener) static package
Creates a NumberPicker.OnValueChangeListener that only executes the given NumberPicker.OnValueChangeListener after 500 ms if the value has not changed.
See also
NumberPicker.OnValueChangeListener
Parameters
originalListener NumberPicker.OnValueChangeListener that is called when the value does not change.
Returns
A NumberPicker.OnValueChangeListener with delayed execution.
Definition at line 152 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter().
Member Data Documentation
abilityPicker
final ValuePicker<Ability> abilityPicker private
ValuePicker used to decide the value of UnitEntity::ability.
See also
#squadPicker
Definition at line 58 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
damagePicker
final DamageValuePicker damagePicker private
DamageValuePicker used to decide the value of UnitEntity::damage.
Definition at line 50 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
EPIC_UNIT_ABILITIES
final List<Ability> EPIC_UNIT_ABILITIES = Arrays.asList(Ability.NONE, Ability.HORN, Ability.MORAL_BOOST) static private
List of Ability values that epic units can have.
Definition at line 38 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter().
epicPicker
final ValuePicker<Boolean> epicPicker private
ValuePicker used to decide the value of UnitEntity::epic.
Definition at line 44 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
numberPicker
final NumberPicker numberPicker private
NumberPicker used to decide the number of UnitEntity objects that are inserted.
Definition at line 78 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
squadManager
final SquadManager squadManager private
SquadManager containing current SquadState used to get squad information.
Definition at line 72 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
squadPicker
final NumberPicker squadPicker private
NumberPicker used to decide the value of UnitEntity::squad.
Only visible if the value of #abilityPicker is set to Ability::BINDING.
See also
#abilityPicker
Definition at line 66 of file CardNumberPickerAdapter.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/addcard/CardNumberPickerAdapter.java