Gwent: DamageCalculatorUseCase Class Reference
DamageCalculatorUseCase Class Reference
A use case class responsible for creating DamageCalculator objects for rows using DamageCalculatorBuildDirector.
Static Public Member Functions
static Single< DamageCalculator > getDamageCalculator (@NonNull UnitRepository repository, @NonNull RowType row)
Returns a Single emitting a DamageCalculator object for the given row with properties retrieved from the given UnitRepository.
static DamageCalculator getDamageCalculator (boolean weather, boolean horn, @NonNull Collection< UnitEntity > units)
Creates a DamageCalculator for a row with the given weather status, horn status and units.
Detailed Description
A use case class responsible for creating DamageCalculator objects for rows using DamageCalculatorBuildDirector.
See also
DamageCalculatorBuildDirector
DamageCalculator
Definition at line 23 of file DamageCalculatorUseCase.java.
Member Function Documentation
getDamageCalculator() [1/2]
static Single< DamageCalculator > getDamageCalculator (@NonNull UnitRepository repository, @NonNull RowType row) static
Returns a Single emitting a DamageCalculator object for the given row with properties retrieved from the given UnitRepository.
Parameters
repository UnitRepository used for data collection.
row RowType defining which row is queried for DamageCalculator generation.
Returns
A Single emitting a DamageCalculator object for the given row.
Definition at line 32 of file DamageCalculatorUseCase.java.
References DamageCalculatorUseCase.getDamageCalculator().
Referenced by BurnDialogUseCase.getBurnUnits(), and DamageCalculatorUseCase.getDamageCalculator().
getDamageCalculator() [2/2]
static DamageCalculator getDamageCalculator (boolean weather, boolean horn, @NonNull Collection< UnitEntity > units) static
Creates a DamageCalculator for a row with the given weather status, horn status and units.
Basically calls DamageCalculatorBuildDirector::getCalculator with the given parameters.
Parameters
weather Boolean defining whether the calculation encompasses the weather debuff.
horn Boolean defining whether a commander's horn is in the row.
units Collection of UnitEntity objects that are in the row.
Returns
A DamageCalculator object capable of calculating damage for the given units.
See also
DamageCalculatorBuildDirector::getCalculator(boolean, boolean, Collection)
Definition at line 50 of file DamageCalculatorUseCase.java.
The documentation for this class was generated from the following file:
gwent/domain/cases/DamageCalculatorUseCase.java