Gwent: SquadManager Class Reference
SquadManager Class Reference
A class used by the CardNumberPickerAdapter to determine the first squad with members or set the default damage according to the squads base damage.
Static Public Attributes
static final int MAX_NR_SQUADS = 3
Integer constant defining how many different squads there may be per row.
Package Functions
SquadManager (@NonNull List< UnitEntity > units)
Constructor of a new SquadManager storing information on the squads of the given units.
int getFirstSquadWithMembers ()
Returns the lowest squad number referring to a squad that has members.
void onSquadChanged (@IntRange(from=1, to=MAX_NR_SQUADS) int newVal, @NonNull DamageValuePicker picker)
Shows a Toast with information about the selected squad and sets the given picker to the SquadState::memberBaseDamage of said squad.
Private Attributes
final SquadState[] states = new SquadState[MAX_NR_SQUADS]
Array of SquadState objects containing one SquadState for each possible squad.
Detailed Description
A class used by the CardNumberPickerAdapter to determine the first squad with members or set the default damage according to the squads base damage.
See also
CardNumberPickerAdapter
Definition at line 24 of file SquadManager.java.
Constructor & Destructor Documentation
SquadManager()
SquadManager (@NonNull List< UnitEntity > units) package
Constructor of a new SquadManager storing information on the squads of the given units.
Parameters
units List of UnitEntity objects that is used to fetch squad information.
Definition at line 41 of file SquadManager.java.
References SquadState.getState(), SquadManager.MAX_NR_SQUADS, and SquadManager.states.
Member Function Documentation
getFirstSquadWithMembers()
int getFirstSquadWithMembers () package
Returns the lowest squad number referring to a squad that has members.
If no squad has members, i.e., there are no units with the Ability::BINDING ability, 1 is returned.
Returns
An Integer referencing to the first squad with members.
Definition at line 55 of file SquadManager.java.
References SquadState.getSquadNumber(), SquadState.hasMembers(), and SquadManager.states.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), and CardNumberPickerAdapter.addSelectedUnits().
onSquadChanged()
void onSquadChanged (@IntRange(from=1, to=MAX_NR_SQUADS) int newVal, @NonNull DamageValuePicker picker) package
Shows a Toast with information about the selected squad and sets the given picker to the SquadState::memberBaseDamage of said squad.
Parameters
newVal Integer representing the newly selected squad.
picker DamageValuePicker that is updated.
Exceptions
IllegalArgumentException When newVal is not between 1 and #MAX_NR_SQUADS.
See also
SquadState::getMemberBaseDamage()
Definition at line 72 of file SquadManager.java.
References SquadState.getMemberBaseDamage(), SquadState.getSquadMembers(), SquadState.getSquadNumber(), SquadState.hasMembers(), SquadManager.MAX_NR_SQUADS, and SquadManager.states.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter().
Member Data Documentation
MAX_NR_SQUADS
final int MAX_NR_SQUADS = 3 static
Integer constant defining how many different squads there may be per row.
Definition at line 28 of file SquadManager.java.
Referenced by CardNumberPickerAdapter.CardNumberPickerAdapter(), SquadManager.SquadManager(), and SquadManager.onSquadChanged().
states
final SquadState [] states = new SquadState[MAX_NR_SQUADS] private
Array of SquadState objects containing one SquadState for each possible squad.
Definition at line 34 of file SquadManager.java.
Referenced by SquadManager.SquadManager(), SquadManager.getFirstSquadWithMembers(), and SquadManager.onSquadChanged().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/addcard/SquadManager.java