Gwent: ShowUnitsDialog Class Reference
ShowUnitsDialog Class Reference
An OverlayDialog used to list the units of a certain row and enabling the user to copy, add, or delete new units.
Public Member Functions
RowType getRow ()
Returns the row this ShowUnitsDialog is representing.
Static Public Member Functions
static Single< ShowUnitsDialog > getDialog (@NonNull Context context, @NonNull RowType row)
Creates a new ShowUnitsDialog in the given Context and for the given row.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Initializes the RecyclerView by connecting it to the cardListAdapter and sets View.OnClickListener for each button.
Protected Member Functions inherited from OverlayDialog
OverlayDialog (@NonNull Context context, @LayoutRes int layout, @IdRes int dismissViewId)
Constructor of an OverlayDialog in the given Context, with the given layout and dismissViewId.
OverlayDialog (@NonNull Context context, @LayoutRes int layout)
Constructor of an OverlayDialog in the given Context and with the given layout.
Private Member Functions
ShowUnitsDialog (@NonNull Context context, @NonNull RowType row, @NonNull CardListAdapter cardListAdapter)
Constructor of a ShowUnitsDialog shown in the given Context and with the given CardListAdapter.
Private Attributes
final RowType row
RowType defining which row is represented by this Dialog.
final CardListAdapter cardListAdapter
CardListAdapter offering a list of CardUiState objects to the UI.
final CompositeDisposable disposables = new CompositeDisposable()
CompositeDisposable keeping track of all subscriptions to observables made by this class.
RecyclerView unitRecyclerView
RecyclerView presenting the units provided by the cardListAdapter.
Additional Inherited Members
Static Package Attributes inherited from OverlayDialog
static final int NO_DISMISS_VIEW = -1
Integer used as dismissViewId, when the Dialog shouldn't be cancelable by clicking on a View.
Detailed Description
An OverlayDialog used to list the units of a certain row and enabling the user to copy, add, or delete new units.
See also
CardListAdapter
Definition at line 29 of file ShowUnitsDialog.java.
Constructor & Destructor Documentation
ShowUnitsDialog()
ShowUnitsDialog (@NonNull Context context, @NonNull RowType row, @NonNull CardListAdapter cardListAdapter) private
Constructor of a ShowUnitsDialog shown in the given Context and with the given CardListAdapter.
Parameters
context Context this Dialog is shown in.
row RowType defining which row all shown units belong to.
cardListAdapter CardListAdapter providing an always up-to-date list of CardUiState objects for a certain row.
Definition at line 66 of file ShowUnitsDialog.java.
References ShowUnitsDialog.cardListAdapter, and ShowUnitsDialog.row.
Referenced by ShowUnitsDialog.getDialog().
Member Function Documentation
getDialog()
static Single<ShowUnitsDialog> getDialog (@NonNull Context context, @NonNull RowType row) static
Creates a new ShowUnitsDialog in the given Context and for the given row.
Parameters
context Context the Dialog is shown in.
row RowType defining the row that is represented by this Dialog.
Returns
A Single emitting the created ShowUnitsDialog.
Definition at line 80 of file ShowUnitsDialog.java.
References ShowUnitsDialog.ShowUnitsDialog(), ShowUnitsDialog.disposables, GwentApplication.getRepository(), RemoveUnitsUseCase.remove(), and ShowUnitsDialog.row.
getRow()
RowType getRow ()
Returns the row this ShowUnitsDialog is representing.
Returns
A RowType defining the represented row.
See also
row
Definition at line 168 of file ShowUnitsDialog.java.
References ShowUnitsDialog.row.
onCreate()
void onCreate (Bundle savedInstanceState) protected
Initializes the RecyclerView by connecting it to the cardListAdapter and sets View.OnClickListener for each button.
Also registers a RecyclerView.AdapterDataObserver responsible for scrolling to the end of the RecyclerView whenever an item is being inserted.
See also
CardListAdapter::registerAdapterDataObserver(RecyclerView.AdapterDataObserver)
Parameters
savedInstanceState If this dialog is being reinitialized after the hosting activity was previously shut down, holds the result from the most recent call to onSaveInstanceState, or null if this is the first time.
Smoothly scrolls to the last item in the RecyclerView to show the user that an item has been inserted.
Parameters
positionStart Integer defining the first position from where new items are inserted.
itemCount Integer defining how many items have been inserted.
See also
RecyclerView::smoothScrollToPosition(int)
Reimplemented from OverlayDialog.
Definition at line 122 of file ShowUnitsDialog.java.
References ShowUnitsDialog.cardListAdapter, ShowUnitsDialog.disposables, and ShowUnitsDialog.unitRecyclerView.
Member Data Documentation
cardListAdapter
final CardListAdapter cardListAdapter private
CardListAdapter offering a list of CardUiState objects to the UI.
Definition at line 42 of file ShowUnitsDialog.java.
Referenced by ShowUnitsDialog.ShowUnitsDialog(), and ShowUnitsDialog.onCreate().
disposables
final CompositeDisposable disposables = new CompositeDisposable() private
CompositeDisposable keeping track of all subscriptions to observables made by this class.
Is being disposed in an android.content.DialogInterface.OnDismissListener that is set in onCreate().
See also
android.content.DialogInterface.OnDismissListener
onCreate(Bundle)
Definition at line 52 of file ShowUnitsDialog.java.
Referenced by ShowUnitsDialog.getDialog(), and ShowUnitsDialog.onCreate().
row
final RowType row private
RowType defining which row is represented by this Dialog.
See also
getRow()
Definition at line 36 of file ShowUnitsDialog.java.
Referenced by ShowUnitsDialog.ShowUnitsDialog(), ShowUnitsDialog.getDialog(), and ShowUnitsDialog.getRow().
unitRecyclerView
RecyclerView unitRecyclerView private
RecyclerView presenting the units provided by the cardListAdapter.
Definition at line 57 of file ShowUnitsDialog.java.
Referenced by ShowUnitsDialog.onCreate().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/cards/ShowUnitsDialog.java