Gwent: CardListAdapter Class Reference
CardListAdapter Class Reference
A ListAdapter used to provide CardListAdapter.CardViewHolder objects created from CardUiState objects to a RecyclerView.
Classes
class CardViewHolder
A RecyclerView.ViewHolder class managing a card view that shows a representation of the UnitEntity referenced by #itemId.
Public Member Functions
CardViewHolder onCreateViewHolder (@NonNull ViewGroup parent, int viewType)
Creates a new CardViewHolder managing a new card view that is inflated from the given parent.
void onBindViewHolder (@NonNull CardViewHolder holder, @IntRange(from=0) int position)
Changes the views of CardViewHolder to represent the item at the given position.
long getItemId (@IntRange(from=0) int position)
Returns the UnitEntity::id of the UnitEntity represented at the given position.
Package Functions
CardListAdapter (@NonNull Consumer< Integer > onCopy, @NonNull Consumer< Integer > onRemove)
Constructor of a CardListAdapter with the given #onCopy and #onRemove callbacks.
Private Attributes
final Consumer< Integer > onCopy
Consumer that is used in #onCreateViewHolder(ViewGroup, int) as CardListAdapter.CardViewHolder::onCopy.
final Consumer< Integer > onRemove
Consumer that is used in #onCreateViewHolder(ViewGroup, int) as CardListAdapter.CardViewHolder::onRemove.
Detailed Description
A ListAdapter used to provide CardListAdapter.CardViewHolder objects created from CardUiState objects to a RecyclerView.
See also
CardUiState
CardListAdapter.CardViewHolder
ListAdapter
RecyclerView
Definition at line 28 of file CardListAdapter.java.
Constructor & Destructor Documentation
CardListAdapter()
CardListAdapter (@NonNull Consumer< Integer > onCopy, @NonNull Consumer< Integer > onRemove) package
Constructor of a CardListAdapter with the given #onCopy and #onRemove callbacks.
Calls super-constructor ListAdapter::ListAdapter(DiffUtil.ItemCallback) with CardUiState::DIFF_CALLBACK. Also calls #setHasStableIds() since #getItemId() returns the stable UnitEntity::id.
See also
ListAdapter::ListAdapter(DiffUtil.ItemCallback)
CardUiState::DIFF_CALLBACK
#setHasStableIds(boolean)
Parameters
onCopy Consumer that is called with the UnitEntity::id, when the copy-button of the representing card is clicked.
onRemove Consumer that is called with the UnitEntity::id, when the delete-button of the representing card is clicked.
Definition at line 65 of file CardListAdapter.java.
References CardUiState.DIFF_CALLBACK, CardListAdapter.onCopy, and CardListAdapter.onRemove.
Member Function Documentation
getItemId()
long getItemId (@IntRange(from=0) int position)
Returns the UnitEntity::id of the UnitEntity represented at the given position.
Parameters
position Adapter position to query.
Returns
A Long referencing the UnitEntity::id of the UnitEntity represented at the given position.
Definition at line 122 of file CardListAdapter.java.
onBindViewHolder()
void onBindViewHolder (@NonNull CardViewHolder holder, @IntRange(from=0) int position)
Changes the views of CardViewHolder to represent the item at the given position.
Parameters
holder The CardViewHolder which should be updated to represent the contents of the item at the given position in the data set.
position The position of the item within the adapter's data set.
Definition at line 93 of file CardListAdapter.java.
References CardUiState.getAbilityImageId(), CardUiState.getDamageBackgroundImageId(), CardUiState.getDamageString(), CardUiState.getDamageTextColor(), CardUiState.getSquadString(), CardUiState.getUnitId(), CardUiState.showAbility(), and CardUiState.showSquad().
onCreateViewHolder()
CardViewHolder onCreateViewHolder (@NonNull ViewGroup parent, int viewType)
Creates a new CardViewHolder managing a new card view that is inflated from the given parent.
Parameters
parent The ViewGroup into which the new View will be added after it is bound to an adapter position.
viewType The view type of the new View.
Returns
A CardViewHolder object for a new card layout and with #onCopy and #onRemove callbacks.
Definition at line 81 of file CardListAdapter.java.
References CardListAdapter.onCopy, and CardListAdapter.onRemove.
Member Data Documentation
onCopy
final Consumer<Integer> onCopy private
Consumer that is used in #onCreateViewHolder(ViewGroup, int) as CardListAdapter.CardViewHolder::onCopy.
Is called when the user clicks on the copy-button of an element with the UnitEntity::id of the represented UnitEntity.
See also
#onCreateViewHolder(ViewGroup, int)
CardListAdapter.CardViewHolder::onCopy
Definition at line 39 of file CardListAdapter.java.
Referenced by CardListAdapter.CardListAdapter(), CardListAdapter.CardViewHolder.CardViewHolder(), and CardListAdapter.onCreateViewHolder().
onRemove
final Consumer<Integer> onRemove private
Consumer that is used in #onCreateViewHolder(ViewGroup, int) as CardListAdapter.CardViewHolder::onRemove.
Is called when the user clicks on the delete-button of an element with the UnitEntity::id of the represented UnitEntity.
See also
#onCreateViewHolder(ViewGroup, int)
CardListAdapter.CardViewHolder::onRemove
Definition at line 50 of file CardListAdapter.java.
Referenced by CardListAdapter.CardListAdapter(), CardListAdapter.CardViewHolder.CardViewHolder(), and CardListAdapter.onCreateViewHolder().
The documentation for this class was generated from the following file:
gwent/ui/dialogs/cards/CardListAdapter.java