Gwent: ResetRepositoryUseCase Class Reference
ResetRepositoryUseCase Class Reference
A use case class responsible for resetting the UnitRepository.
Static Public Member Functions
static Completable reset (@NonNull Context context, @NonNull UnitRepository repository, @NonNull SoundManager soundManager)
Resets the given UnitRepository.
Static Package Functions
static Maybe< UnitEntity > reset (@NonNull Context context, @NonNull UnitRepository repository, boolean keepUnit, @NonNull SoundManager soundManager)
Resets the given UnitRepository and keeps one random unit if keepUnit is true.
Static Private Member Functions
static Optional< UnitEntity > getRandomUnit (@NonNull List< UnitEntity > units)
Selects a random unit that is not epic.
static Dialog getRevengeDialog (@NonNull Context context, @NonNull UnitRepository repository, @NonNull CompletableEmitter emitter, @Nullable UnitEntity keptUnit, @IntRange(from=1) int revengeUnits, @NonNull SoundManager soundManager)
Creates a Dialog asking whether the Ability::REVENGE ability should be activated.
Detailed Description
A use case class responsible for resetting the UnitRepository.
Capable of invoking a Dialog if a UnitEntity with the Ability::REVENGE ability is removed. Should not be used directly by the UI layer.
See also
ResetDialogUseCase
Definition at line 31 of file ResetRepositoryUseCase.java.
Member Function Documentation
getRandomUnit()
static Optional< UnitEntity > getRandomUnit (@NonNull List< UnitEntity > units) static private
Selects a random unit that is not epic.
If all units are epic or if there are no units at all, an empty Optional is returned.
Parameters
units List of UnitEntity objects, one of which is selected.
Returns
An Optional containing the selected unit or nothing if no unit could be selected.
Definition at line 71 of file ResetRepositoryUseCase.java.
Referenced by ResetRepositoryUseCase.reset().
getRevengeDialog()
static Dialog getRevengeDialog (@NonNull Context context, @NonNull UnitRepository repository, @NonNull CompletableEmitter emitter, @Nullable UnitEntity keptUnit, @IntRange(from=1) int revengeUnits, @NonNull SoundManager soundManager) static private
Creates a Dialog asking whether the Ability::REVENGE ability should be activated.
The Dialog is created using an RevengeAlertDialogBuilderAdapter.
Parameters
context Context of the shown Dialog.
repository UnitRepository where the UnitEntity objects are removed and avengers are inserted.
emitter CompletableEmitter where CompletableEmitter::onComplete must be called, when the user makes a decision.
keptUnit UnitEntity that should be kept.
revengeUnits Long representing the number of revenge units.
soundManager SoundManager used, if an Avenger is added.
Returns
A Dialog asking whether the Ability::REVENGE ability should be activated.
See also
RevengeAlertDialogBuilderAdapter::insertAvengers(UnitRepository, int, SoundManager)
Definition at line 93 of file ResetRepositoryUseCase.java.
References RevengeAlertDialogBuilderAdapter.create(), RevengeAlertDialogBuilderAdapter.insertAvengers(), and RevengeAlertDialogBuilderAdapter.setPositiveCallback().
Referenced by ResetRepositoryUseCase.reset().
reset() [1/2]
static Completable reset (@NonNull Context context, @NonNull UnitRepository repository, @NonNull SoundManager soundManager) static
Resets the given UnitRepository.
If a removed UnitEntity has the Ability::REVENGE ability, a Dialog asking whether the ability should be used is shown. Wrapper of #reset(Context, UnitRepository, boolean, SoundManager).
Parameters
context Context of the shown Dialog.
repository UnitRepository that is being reset.
soundManager SoundManager used, if an UnitEntity has the Ability::REVENGE ability.
Returns
A Completable tracking operation status.
See also
#reset(Context, UnitRepository, boolean, SoundManager)
Definition at line 123 of file ResetRepositoryUseCase.java.
References ResetRepositoryUseCase.reset().
reset() [2/2]
static Maybe< UnitEntity > reset (@NonNull Context context, @NonNull UnitRepository repository, boolean keepUnit, @NonNull SoundManager soundManager) static package
Resets the given UnitRepository and keeps one random unit if keepUnit is true.
If a removed UnitEntity has the Ability::REVENGE ability, a Dialog asking whether the ability should be used is shown.
Parameters
context Context of the shown Dialog.
repository UnitRepository that is being reset.
keepUnit Boolean defining whether a single UnitEntity should be kept.
soundManager SoundManager used, if an UnitEntity has the Ability::REVENGE ability.
Returns
A Maybe emitting the kept UnitEntity or nothing if keepUnit is false.
See also
#getRevengeDialog(Context, UnitRepository, CompletableEmitter, UnitEntity, int, SoundManager)
UnitRepository::reset(UnitEntity)
Definition at line 46 of file ResetRepositoryUseCase.java.
References ResetRepositoryUseCase.getRandomUnit(), and ResetRepositoryUseCase.getRevengeDialog().
Referenced by ResetRepositoryUseCase.reset(), and ResetDialogUseCase.reset().
The documentation for this class was generated from the following file:
gwent/domain/cases/ResetRepositoryUseCase.java