Gwent: AppDatabase Class Reference
AppDatabase Class Reference abstract
An abstract class extending RoomDatabase and representing the SQLite database of the application.
Package Functions
abstract UnitDao units ()
Returns an object implementing the operations defined in UnitDao.
abstract RowDao rows ()
Returns an object implementing the operations defined in RowDao.
Detailed Description
An abstract class extending RoomDatabase and representing the SQLite database of the application.
The implementation is generated by the Room framework.
Definition at line 11 of file AppDatabase.java.
Member Function Documentation
rows()
abstract RowDao rows () abstract package
Returns an object implementing the operations defined in RowDao.
Returns
RowDao implementing DAO for rows table.
Referenced by UnitRepository.clearWeather(), UnitRepository.initializeRows(), UnitRepository.isHorn(), UnitRepository.isHornFlowable(), UnitRepository.isWeather(), UnitRepository.isWeatherFlowable(), UnitRepository.reset(), UnitRepository.switchHorn(), and UnitRepository.switchWeather().
units()
abstract UnitDao units () abstract package
Returns an object implementing the operations defined in UnitDao.
Returns
UnitDao implementing DAO for units table.
Referenced by UnitRepository.countUnits(), UnitRepository.countUnits(), UnitRepository.delete(), UnitRepository.delete(), UnitRepository.getUnit(), UnitRepository.getUnits(), UnitRepository.getUnits(), UnitRepository.getUnitsFlowable(), UnitRepository.hasNonEpicUnitsFlowable(), UnitRepository.insertUnit(), and UnitRepository.reset().
The documentation for this class was generated from the following file:
gwent/data/AppDatabase.java