Gwent: MainActivity Class Reference
MainActivity Class Reference
An AppCompatActivity that is called on startup and that encapsulates the main view onto the game board.
Public Member Functions
void onWindowFocusChanged (boolean hasFocus)
Called when the focus of this activities android.view.Window changes.
Protected Member Functions
void onCreate (@Nullable Bundle savedInstanceState)
Sets the theme and layout, initializes gameBoardViewModel and factionSwitchListener and sets listeners for some menu buttons.
void onResume ()
Called when the application is resumed after a pause or on startup.
void onDestroy ()
Called when the activity is destroyed.
Private Member Functions
void initializeViewModel ()
Initializes the Views in this activity to communicate with the gameBoardViewModel.
void inflateFactionPopup ()
Shows a new ChangeFactionDialog enabling the user to choose the preferred theme.
void inflateCoinFlipPopup ()
Shows a new CoinFlipDialog and plays a coin-flip sound using SoundManager#playCoinSound().
Private Attributes
final CompositeDisposable disposables = new CompositeDisposable()
CompositeDisposable used to store all io.reactivex.rxjava3.disposables.Disposables, this activity might create to allow for their disposal in onDestroy().
SharedPreferences.OnSharedPreferenceChangeListener factionSwitchListener
SharedPreferences.OnSharedPreferenceChangeListener that is called when faction-layout, i.e., the androidx.preference.Preference at the key defined by com.peternaggschga.gwent.ui.main.FactionSwitchListener#THEME_PREFERENCE_KEY, is changed.
GameBoardViewModel gameBoardViewModel
GameBoardViewModel holding the ui state of this activity.
Detailed Description
An AppCompatActivity that is called on startup and that encapsulates the main view onto the game board.
Definition at line 46 of file MainActivity.java.
Member Function Documentation
inflateCoinFlipPopup()
void inflateCoinFlipPopup () private
Shows a new CoinFlipDialog and plays a coin-flip sound using SoundManager#playCoinSound().
Definition at line 274 of file MainActivity.java.
References MainActivity.gameBoardViewModel, and GameBoardViewModel.getSoundManager().
Referenced by MainActivity.onCreate().
inflateFactionPopup()
void inflateFactionPopup () private
Shows a new ChangeFactionDialog enabling the user to choose the preferred theme.
The decision is saved in the preference at the key FactionSwitchListener#THEME_PREFERENCE_KEY and if the user opted to reset on faction switch (i.e., the preference at R.string#preference_key_faction_reset is true), GameBoardViewModel#onFactionSwitchReset(Context) is called.
Definition at line 250 of file MainActivity.java.
References MainActivity.disposables, MainActivity.gameBoardViewModel, and GameBoardViewModel.onFactionSwitchReset().
Referenced by MainActivity.onCreate().
initializeViewModel()
void initializeViewModel () private
Initializes the Views in this activity to communicate with the gameBoardViewModel.
Sets android.widget.Button.OnClickListener for the weather-, horn-, and card-views of each row as well as listeners for the reset-, weather- and burn-buttons.
Definition at line 191 of file MainActivity.java.
References MainActivity.disposables, MainActivity.gameBoardViewModel, GameBoardViewModel.getMenuUiState(), RowUiStateObserver.getObserver(), GwentApplication.getRepository(), GameBoardViewModel.getRowUiState(), GameBoardViewModel.getSoundManager(), GameBoardViewModel.onBurnButtonPressed(), GameBoardViewModel.onHornViewPressed(), GameBoardViewModel.onResetButtonPressed(), GameBoardViewModel.onWeatherButtonPressed(), and GameBoardViewModel.onWeatherViewPressed().
Referenced by MainActivity.onCreate().
onCreate()
void onCreate (@Nullable Bundle savedInstanceState) protected
Sets the theme and layout, initializes gameBoardViewModel and factionSwitchListener and sets listeners for some menu buttons.
If the application is started for the first time (as tracked by the preference at key R.string#preference_first_use_key) the IntroductionActivity is called first. The theme is set according to the preference at the key specified by FactionSwitchListener#THEME_PREFERENCE_KEY. The layout is set to R.layout#activity_main. android.widget.Button.OnClickListeners are set for the buttons referenced by R.id#factionButton, R.id#coinButton, and R.id#settingsButton.
Parameters
savedInstanceState If the activity is being re-initialized after previously being shut down then this Bundle contains the data it most recently supplied in onSaveInstanceState. Note: Otherwise it is null.
Definition at line 83 of file MainActivity.java.
References MainActivity.disposables, MainActivity.factionSwitchListener, MainActivity.gameBoardViewModel, FactionSwitchListener.getListener(), GameBoardViewModel.getModel(), GwentApplication.getRepository(), MainActivity.inflateCoinFlipPopup(), MainActivity.inflateFactionPopup(), MainActivity.initializeViewModel(), and FactionSwitchListener.setTheme().
onDestroy()
void onDestroy () protected
Called when the activity is destroyed.
Disposes and clears all io.reactivex.rxjava3.disposables.Disposables in disposables.
Definition at line 180 of file MainActivity.java.
References MainActivity.disposables.
onResume()
void onResume () protected
Called when the application is resumed after a pause or on startup.
Sets the background image according to the preference at the key referenced by R.string#preference_key_design.
Definition at line 124 of file MainActivity.java.
onWindowFocusChanged()
void onWindowFocusChanged (boolean hasFocus)
Called when the focus of this activities android.view.Window changes.
Hides system ui and sets flags to keep the screen on when the window is in focus for more than 250 ms.
Parameters
hasFocus Whether the window of this activity has focus.
Definition at line 154 of file MainActivity.java.
Member Data Documentation
disposables
final CompositeDisposable disposables = new CompositeDisposable() private
CompositeDisposable used to store all io.reactivex.rxjava3.disposables.Disposables, this activity might create to allow for their disposal in onDestroy().
Definition at line 52 of file MainActivity.java.
Referenced by MainActivity.inflateFactionPopup(), MainActivity.initializeViewModel(), MainActivity.onCreate(), and MainActivity.onDestroy().
factionSwitchListener
SharedPreferences.OnSharedPreferenceChangeListener factionSwitchListener private
SharedPreferences.OnSharedPreferenceChangeListener that is called when faction-layout, i.e., the androidx.preference.Preference at the key defined by com.peternaggschga.gwent.ui.main.FactionSwitchListener#THEME_PREFERENCE_KEY, is changed.
Reference must be kept (even if not used) to avoid garbage collection of the registered listener (see here for more information).
Definition at line 61 of file MainActivity.java.
Referenced by MainActivity.onCreate().
gameBoardViewModel
GameBoardViewModel gameBoardViewModel private
GameBoardViewModel holding the ui state of this activity.
Definition at line 66 of file MainActivity.java.
Referenced by MainActivity.inflateCoinFlipPopup(), MainActivity.inflateFactionPopup(), MainActivity.initializeViewModel(), and MainActivity.onCreate().
The documentation for this class was generated from the following file:
gwent/ui/main/MainActivity.java