Gwent: DamageCalculator Interface Reference
DamageCalculator Interface Reference
An interface for a class capable of calculating the (de-)buffed damage of a unit for a given UnitEntity::id and UnitEntity::damage.
Classes
enum Color
An enum containing values representing whether a unit is buffed, de-buffed or not affected by status effects.
Public Member Functions
Color isBuffed (int id)
Calculates whether the unit with the given id is shown as Color::BUFFED, Color::DEBUFFED, or Color::DEFAULT.
int calculateDamage (int id, @IntRange(from=0) int damage)
Calculates the (de-)buffed damage of unit with the given id and the given base-damage.
Detailed Description
An interface for a class capable of calculating the (de-)buffed damage of a unit for a given UnitEntity::id and UnitEntity::damage.
Is used to implement the visitor design pattern, see com.peternaggschga.gwent.data.UnitEntity::calculateDamage() The respective visitors are created as a decorator hierarchy, see DamageCalculatorBuildDirector::getCalculator().
See also
com.peternaggschga.gwent.data.UnitEntity::calculateDamage(DamageCalculator)
DamageCalculatorBuildDirector::getCalculator(boolean, boolean, Collection)
Definition at line 17 of file DamageCalculator.java.
Member Function Documentation
calculateDamage()
int calculateDamage (int id, @IntRange(from=0) int damage)
Calculates the (de-)buffed damage of unit with the given id and the given base-damage.
Calculation is defined by the underlying decorator structure implemented via DamageCalculatorDecorator and WeatherDamageCalculator.
Parameters
id Integer representing the UnitEntity::id of the unit whose (de-)buff damage is calculated.
damage Integer representing the base-damage of the unit whose (de-)buff damage is calculated.
Returns
Integer representing the (de-)buffed damage of the unit.
See also
DamageCalculatorDecorator
WeatherDamageCalculator
Implemented in BondDamageCalculatorDecorator, HornDamageCalculatorDecorator, MoralDamageCalculatorDecorator, and WeatherDamageCalculator.
Referenced by BondDamageCalculatorDecorator.calculateDamage(), HornDamageCalculatorDecorator.calculateDamage(), and MoralDamageCalculatorDecorator.calculateDamage().
isBuffed()
Color isBuffed (int id)
Calculates whether the unit with the given id is shown as Color::BUFFED, Color::DEBUFFED, or Color::DEFAULT.
Units are shown as Color::DEFAULT when they are not affected by any damage changing buffs or de-buffs. Units are shown as Color::DEBUFFED when they are only affected by the weather de-buff. Units are shown as Color::BUFFED when they are affected by any damage-increasing buff.
Parameters
id Integer representing the UnitEntity::id of the unit buff status is calculated.
Returns
Color representing whether the unit is buffed, de-buffed or not affected.
See also
Color
Implemented in BondDamageCalculatorDecorator, HornDamageCalculatorDecorator, MoralDamageCalculatorDecorator, and WeatherDamageCalculator.
Referenced by BondDamageCalculatorDecorator.isBuffed(), HornDamageCalculatorDecorator.isBuffed(), and MoralDamageCalculatorDecorator.isBuffed().
The documentation for this interface was generated from the following file:
gwent/domain/damage/DamageCalculator.java