Gwent: UnitDao Interface Reference
UnitDao Interface Reference
An interface defining data access operations related to units table.
Public Member Functions
Completable insertUnit (@NonNull UnitEntity unit)
Inserts the given UnitEntity into units.
Completable insertUnit (boolean epic, @IntRange(from=0, to=UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row)
Inserts a UnitEntity with the given values into units.
Completable deleteUnit (int id)
Deletes the UnitEntity object with the given id from units.
Completable deleteUnits (@NonNull Collection< UnitEntity > units)
Deletes the given UnitEntity objects from units.
Single< UnitEntity > getUnit (int id)
Fetches the UnitEntity object with the given id from units.
Single< List< UnitEntity > > getUnits (@NonNull RowType row)
Fetches all UnitEntity objects from units in the given row.
Flowable< List< UnitEntity > > getUnitsFlowable (@NonNull RowType row)
Fetches a Flowable for all UnitEntity objects from units in the given row.
Single< List< UnitEntity > > getUnits ()
Fetches all UnitEntity objects from units.
Single< Integer > countUnits (@NonNull RowType row)
Counts UnitEntity objects in units in the given row.
Single< Integer > countUnits ()
Counts UnitEntity objects in units.
Flowable< Boolean > hasNonEpicUnitsFlowable ()
Fetches a Flowable of Booleans defining whether units contains units that are not epic.
Detailed Description
An interface defining data access operations related to units table.
The implementation is generated by the Room framework.
Definition at line 25 of file UnitDao.java.
Member Function Documentation
countUnits() [1/2]
Single< Integer > countUnits ()
Counts UnitEntity objects in units.
Returns
A Single tracking operation status and returning the value.
countUnits() [2/2]
Single< Integer > countUnits (@NonNull RowType row)
Counts UnitEntity objects in units in the given row.
Parameters
row RowType defining the UnitEntity::row foreign key.
Returns
A Single tracking operation status and returning the value.
Referenced by UnitRepository.countUnits(), and UnitRepository.countUnits().
deleteUnit()
Completable deleteUnit (int id)
Deletes the UnitEntity object with the given id from units.
Parameters
id Integer representing the UnitEntity::id of the deleted UnitEntity.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.delete().
deleteUnits()
Completable deleteUnits (@NonNull Collection< UnitEntity > units)
Deletes the given UnitEntity objects from units.
Parameters
units List of UnitEntity that are being inserted.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.delete().
getUnit()
Single< UnitEntity > getUnit (int id)
Fetches the UnitEntity object with the given id from units.
Parameters
id Integer representing the UnitEntity::id of the requested UnitEntity.
Returns
A Single tracking operation status and returning the value.
Referenced by UnitRepository.getUnit().
getUnits() [1/2]
Single< List< UnitEntity > > getUnits ()
Fetches all UnitEntity objects from units.
Returns
A Single tracking operation status and returning the value.
getUnits() [2/2]
Single< List< UnitEntity > > getUnits (@NonNull RowType row)
Fetches all UnitEntity objects from units in the given row.
See also
#getUnitsFlowable(RowType)
Parameters
row RowType defining the UnitEntity::row foreign key.
Returns
A Single tracking operation status and returning the value.
Referenced by UnitRepository.getUnits(), and UnitRepository.getUnits().
getUnitsFlowable()
Flowable< List< UnitEntity > > getUnitsFlowable (@NonNull RowType row)
Fetches a Flowable for all UnitEntity objects from units in the given row.
Parameters
row RowType defining the UnitEntity::row foreign key.
Returns
A Flowable emitting the values.
See also
#getUnits(RowType)
Referenced by UnitRepository.getUnitsFlowable().
hasNonEpicUnitsFlowable()
Flowable< Boolean > hasNonEpicUnitsFlowable ()
Fetches a Flowable of Booleans defining whether units contains units that are not epic.
Returns
A Flowable emitting the values.
Referenced by UnitRepository.hasNonEpicUnitsFlowable().
insertUnit() [1/2]
Completable insertUnit (@NonNull UnitEntity unit)
Inserts the given UnitEntity into units.
If the same UnitEntity::id is already in the table, the new insert is ignored.
Parameters
unit UnitEntity that is being inserted.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.insertUnit(), and UnitRepository.reset().
insertUnit() [2/2]
Completable insertUnit (boolean epic, @IntRange(from=0, to=UnitEntity.NON_EPIC_DAMAGE_VALUES_UPPER_BOUND) int damage, @NonNull Ability ability, @IntRange(from=1) @Nullable Integer squad, @NonNull RowType row)
Inserts a UnitEntity with the given values into units.
Parameters
epic Boolean defining whether the unit is epic.
damage Non-Negative value defining the base-damage of the unit.
ability Ability defining the ability of the unit.
squad Non-Negative value defining the squad of units, if UnitEntity::ability is Ability::BINDING, or null.
row RowType defining the UnitEntity::row foreign key.
Returns
A Completable tracking operation status.
The documentation for this interface was generated from the following file:
gwent/data/UnitDao.java