Gwent: RowDao Interface Reference
RowDao Interface Reference
An interface defining data access operations related to rows table.
Public Member Functions
Completable insertRow (@NonNull RowEntity row)
Inserts the given RowEntity into rows.
Completable clearRows ()
Deletes all RowEntity objects from rows.
Completable updateWeather (@NonNull RowType row)
Flips RowEntity::weather for the given RowType in rows.
Completable clearWeather ()
Sets RowEntity::weather to false for all RowEntity elements in rows.
Completable updateHorn (@NonNull RowType row)
Flips RowEntity::horn for the given RowType in rows.
Single< Boolean > isWeather (@NonNull RowType row)
Fetches RowEntity::weather for the given RowType in rows.
Flowable< Boolean > isWeatherFlowable (@NonNull RowType row)
Fetches a Flowable of RowEntity::weather for the given RowType in rows.
Single< Boolean > isHorn (@NonNull RowType row)
Fetches RowEntity::horn for the given RowType in rows.
Flowable< Boolean > isHornFlowable (@NonNull RowType row)
Fetches a Flowable of RowEntity::horn for the given RowType in rows.
Detailed Description
An interface defining data access operations related to rows table.
The implementation is generated by the Room framework.
Definition at line 19 of file RowDao.java.
Member Function Documentation
clearRows()
Completable clearRows ()
Deletes all RowEntity objects from rows.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.reset().
clearWeather()
Completable clearWeather ()
Sets RowEntity::weather to false for all RowEntity elements in rows.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.clearWeather().
insertRow()
Completable insertRow (@NonNull RowEntity row)
Inserts the given RowEntity into rows.
If the same RowType is already in the table, the new insert is ignored.
Parameters
row RowEntity that is being inserted.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.initializeRows().
isHorn()
Single< Boolean > isHorn (@NonNull RowType row)
Fetches RowEntity::horn for the given RowType in rows.
See also
#isHornFlowable(RowType)
Parameters
row RowType of the queried RowEntity.
Returns
A Single tracking operation status and returning the value.
Referenced by UnitRepository.isHorn().
isHornFlowable()
Flowable< Boolean > isHornFlowable (@NonNull RowType row)
Fetches a Flowable of RowEntity::horn for the given RowType in rows.
Parameters
row RowType of the queried RowEntity.
Returns
A Flowable emitting the values.
See also
#isHorn(RowType)
Referenced by UnitRepository.isHornFlowable().
isWeather()
Single< Boolean > isWeather (@NonNull RowType row)
Fetches RowEntity::weather for the given RowType in rows.
See also
#isWeatherFlowable(RowType)
Parameters
row RowType of the queried RowEntity.
Returns
A Single tracking operation status and returning the value.
Referenced by UnitRepository.isWeather().
isWeatherFlowable()
Flowable< Boolean > isWeatherFlowable (@NonNull RowType row)
Fetches a Flowable of RowEntity::weather for the given RowType in rows.
Parameters
row RowType of the queried RowEntity.
Returns
A Flowable emitting the values.
See also
#isWeather(RowType)
Referenced by UnitRepository.isWeatherFlowable().
updateHorn()
Completable updateHorn (@NonNull RowType row)
Flips RowEntity::horn for the given RowType in rows.
Parameters
row RowType of the updated RowEntity.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.switchHorn().
updateWeather()
Completable updateWeather (@NonNull RowType row)
Flips RowEntity::weather for the given RowType in rows.
Parameters
row RowType of the updated RowEntity.
Returns
A Completable tracking operation status.
Referenced by UnitRepository.switchWeather().
The documentation for this interface was generated from the following file:
gwent/data/RowDao.java