Gwent: ResetAlertDialogBuilderAdapter.Callback Interface Reference
ResetAlertDialogBuilderAdapter.Callback Interface Reference
An interface defining functions to propagate the user's decision back to the creator.
Public Member Functions
void reset (boolean resetDecision, boolean keepUnit)
Called when the user makes a decision.
default void reset (boolean resetDecision)
Wrapper for reset(boolean, boolean).
Detailed Description
An interface defining functions to propagate the user's decision back to the creator.
Definition at line 98 of file ResetAlertDialogBuilderAdapter.java.
Member Function Documentation
reset() [1/2]
default void reset (boolean resetDecision)
Wrapper for reset(boolean, boolean).
Can be used when the AlertDialog is not a monster dialog since it calls reset(boolean, boolean) without keeping a unit.
Parameters
resetDecision Boolean defining whether the user has confirmed the reset.
See also
reset(boolean, boolean)
Definition at line 117 of file ResetAlertDialogBuilderAdapter.java.
References ResetAlertDialogBuilderAdapter.Callback.reset().
reset() [2/2]
void reset (boolean resetDecision, boolean keepUnit)
Called when the user makes a decision.
When the AlertDialog is a monster dialog, reset(boolean) can be used.
Parameters
resetDecision Boolean defining whether the user has confirmed the reset.
keepUnit Boolean defining whether a random unit should be kept when resetting.
See also
reset(boolean)
Referenced by ResetAlertDialogBuilderAdapter.ResetAlertDialogBuilderAdapter(), ResetAlertDialogBuilderAdapter.Callback.reset(), and ResetAlertDialogBuilderAdapter.setMonsterDialog().
The documentation for this interface was generated from the following file:
gwent/domain/cases/ResetAlertDialogBuilderAdapter.java